### ISSUE TITLE
[BUG] svg-placeholder-generator custom text not supported chines

### ISSUE THREAD

**Issue by Chanzhaoyu** [CorentinTh/it-tools#1004]
<img width="1446" alt="image" src="https://github.com/CorentinTh/it-tools/assets/24789441/8c92930f-0210-4e6c-bb2d-70a4c347f58a">

**Comment by sharevb** [comment]
Hi @Chanzhaoyu and @CorentinTh, fixed in #905

**Comment by Chanzhaoyu** [comment]
> Hi @Chanzhaoyu and @CorentinTh, fixed in #905嗨，@Chanzhaoyu和@CorentinTh，已修复在 #905 中

great
