### ISSUE TITLE
[TOOL IMPROVEMENT] Phone parser and formatter: Remeber Default country code

### ISSUE THREAD

**Issue by cachius** [CorentinTh/it-tools#1040]
**Describe the solution you'd like**
Phone parser and formatter should remember the "Default country code" from the last time when re-opening the tool.

**Additional context**
I always use the same country code and have to set it on every visit.

**Comment by sharevb** [comment]
Will probably make a PR

**Comment by sharevb** [comment]
Hi @cachius and @CorentinTh, fixed in #1107

**Comment by cachius** [comment]
Great, thanks a lot!
