### ISSUE TITLE
Help! how to set chinese as default language

### ISSUE THREAD

**Issue by gimgoo** [CorentinTh/it-tools#1041]
I want to set Chinese as the default language by changing the code, can you tell me where to change the configuration?

**Comment by cchina** [comment]
![ittools-i18n](https://github.com/CorentinTh/it-tools/assets/5494598/b80c1b74-0e18-4ccf-9c0d-3abe73ac5137)

**Comment by CorentinTh** [comment]
Hello, 

As stated by @cchina, it's in this file, line 8 [src/plugins/i18n.plugin.ts](https://github.com/CorentinTh/it-tools/blob/main/src/plugins/i18n.plugin.ts#L8)

**Comment by thinkcodee** [comment]
使用docker镜像部署，有没有方法设置一个环境变量？（没有重新编译打包，制作镜像）

**Comment by hllshiro** [comment]
So, how do you modify it when deploying with docker?
