### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wkissw** [CorentinTh/it-tools#1045]
jwt 工具遇到长文本显示异常

输入框直接就展示不全了， 也没横向滚动条，根本看不了两边的信息
<img width="1553" alt="image" src="https://github.com/CorentinTh/it-tools/assets/18184630/d44ff28e-0ae6-437b-990f-a043468a520e">

**Comment by sharevb** [comment]
HI @wkissw and @CorentinTh, fixed in #1095
