### ISSUE TITLE
spring cron tool

### ISSUE THREAD

**Issue by githubyong** [CorentinTh/it-tools#1074]
**What tool do you want?**
spring crontab 
**Describe the solution you'd like**
simlar with linux crontab

**Is their example of this tool in the wild?**
 linux crontab

**Comment by noxsii** [comment]
https://it-tools.tech/crontab-generator ?!?

**Comment by CorentinTh** [comment]
Already implemented in it-tools : https://it-tools.tech/crontab-generator

**Comment by githubyong** [comment]
yes,itis.
I think it for linux crontab only before.

**Comment by githubyong** [comment]
could it list last 10 runs time
