### ISSUE TITLE
xml formatter, the right panel is not fully displayed

### ISSUE THREAD

**Issue by tudan110** [CorentinTh/it-tools#1097]
### Describe the bug

When there is too much content in a row, the right panel will be squeezed below and the display will be incomplete.

Under normal circumstances

![image](https://github.com/CorentinTh/it-tools/assets/29975209/21e55805-b99b-40b7-b815-30594db5c753)

under abnormal circumstances

![image](https://github.com/CorentinTh/it-tools/assets/29975209/800c3436-1ee7-4a15-b7e5-3debddbd5ff6)

![image](https://github.com/CorentinTh/it-tools/assets/29975209/39636720-e31c-4ad2-85a1-33b26cc443c6)

### What happened?

A bug happened!

### System information

  System:
    OS: macOS 13.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 13.71 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 124.0.6367.207
    Edge: 124.0.2478.105
    Safari: 17.2.1

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by gitmotion** [comment]
![demo](https://github.com/user-attachments/assets/137557f4-2363-4749-9d16-4575bde70943)

**Comment by tudan110** [comment]
@gitmotion Thanks for the reminder. The new version has indeed been fixed.
