### ISSUE TITLE
Favorites are not displayed

### ISSUE THREAD

**Issue by mrxxxxxx** [CorentinTh/it-tools#1110]
### Describe the bug

No favorites are displayed in the side menu in the German language, but it works perfectly in all other selectable languages.

### What happened?

A bug happened!

### System information

On Synology 1621xs+ as Docker/Container Version.

### Where did you encounter the bug?

Other (installations, docker, etc.)

**Comment by lostars** [comment]
same problem for me. add to favorite from home using english, but add to favorite from tool detail page using your current language. that's the reason.
![image](https://github.com/CorentinTh/it-tools/assets/13404175/1bcacd98-eec2-4a65-89c1-6d5d42171b07)

**Comment by sharevb** [comment]
Hi, will make a PR soon

**Comment by sharevb** [comment]
Hi @mrxxxxxx, @lostars and @CorentinTh, fixed in #1202 (with fallback for existing stored favorites), can be tested at https://it-tools-git-fork-sharevb-fix-ad4f70-corentin-thomasset-s-team.vercel.app/
