### ISSUE TITLE
SM2, SM3, and SM4

### ISSUE THREAD

**Issue by f1998-ai** [CorentinTh/it-tools#1151]
### What type of request is this?

New feature for an existing tool

### Clear and concise description of the feature you are proposing

cryptographic algorithm

### Is their example of this tool in the wild?

https://www.npmjs.com/package/sm-crypto

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by sharevb** [comment]
Hi @f1998-ai , may be will implement in https://github.com/sharevb/it-tools
