### ISSUE TITLE
是否可以支持 json 转 java 实体

### ISSUE THREAD

**Issue by yklove** [CorentinTh/it-tools#1172]
### What type of request is this?

New tool idea

### Clear and concise description of the feature you are proposing

可以参考类似的功能：https://www.json.cn/json2java/
有个小功能点：json中，有的字段都是以下划线命名的，但是Java大部分都要求是驼峰，是不是可以添加选项，用于字段名称转换。

### Is their example of this tool in the wild?

https://www.json.cn/json2java/

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by lemon8866** [comment]
也许你可以看一下
https://github.com/lemon8866/it-tools/blob/translate/src/tools/json-to-java/json-to-java.vue

**Comment by yklove** [comment]
> 也许你可以看一下 https://github.com/lemon8866/it-tools/blob/translate/src/tools/json-to-java/json-to-java.vue 示例:https://tools.uixui.com/json-to-java

我在首页的链接中没有看到这个功能，这个是不是需要更新下了

<img width="1277" alt="image" src="https://github.com/CorentinTh/it-tools/assets/12585320/8c5f112a-0976-4152-85f3-c9cc52b9f65c">


<img width="290" alt="image" src="https://github.com/CorentinTh/it-tools/assets/12585320/c4d7c1bb-06cf-4a9d-a8c3-5f4ad55568fd">

**Comment by lemon8866** [comment]
这个模块 目前仅在我fork 的仓库里有 暂时没有提交PR 所以官方暂时没有json to java   docker 是qingfeng2336/it-tools ，如果确实需要后边我整理一下提交PR

**Comment by sharevb** [comment]
Hi, for people interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)
