### ISSUE TITLE
Emoji: search function lags

### ISSUE THREAD

**Issue by RichardHausgartner** [CorentinTh/it-tools#1176]
### Describe the bug

1. Open https://it-tools.tech/emoji-picker
2. search, f.e. `grin`
3. Some icons appear, but the browser seams to lag during search.

### What happened?

A bug happened!

### System information

Firefox 127.0

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by sharevb** [comment]
Hi @RichardHausgartner and @CorentinTh, implemented debouncing in search fields so that typing is more fluent

**Comment by uveshnizam043** [comment]
Is this is issue close

**Comment by sharevb** [comment]
Hi @uveshnizam043 and @RichardHausgartner, is it ok for you (no or less lag), if you visit the version of my PR https://it-tools-git-fork-sharevb-fix-7522a4-corentin-thomasset-s-team.vercel.app/
