### ISSUE TITLE
urlhunter 

### ISSUE THREAD

**Issue by blobberbun** [CorentinTh/it-tools#1222]
### What type of request is this?

New tool idea

### Clear and concise description of the feature you are proposing

A tool for exposing the destination for links generated by a link-shortening tool

### Is their example of this tool in the wild?

https://github.com/utkusen/urlhunter

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by sharevb** [comment]
Hi @blobberbun, unfortunately, this cannot be done on Client Side only, requires a server side in Go (that is not possible with this project).
