### ISSUE TITLE
[New Tool] - Image file of QR -> QR output

### ISSUE THREAD

**Issue by jamess60** [CorentinTh/it-tools#1224]
### What type of request is this?

New tool idea

### Clear and concise description of the feature you are proposing

I want to upload a QR code as a png/jpeg etc and have IT Tools tell me what type of QR code it is (wifi, text, url etc) and what the value is. 

### Is their example of this tool in the wild?

[Probably?](https://zxing.org/w/decode.jspx)

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by sharevb** [comment]
Hi @jamess60  (and @CorentinTh), implemented in https://github.com/CorentinTh/it-tools/pull/914 but still not merged

**Comment by jamess60** [comment]
Ah neat, I didnt see that one. Ill close as duplicate, thanks :)

**Comment by sharevb** [comment]
Hi @jamess60 and @CorentinTh, added common qr code type parsing in #914

**Comment by sharevb** [comment]
Hi @jamess60 and, for people interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)
