### ISSUE TITLE
curl command converter

### ISSUE THREAD

**Issue by GitCourser** [CorentinTh/it-tools#1225]
### What type of request is this?

New tool idea

### Clear and concise description of the feature you are proposing

Convert `curl` commands into various programming language codes, because the request can be easily copied into `curl` commands in the browser

### Is their example of this tool in the wild?

like this
[https://curlconverter.com](https://curlconverter.com)
[https://github.com/curlconverter/curlconverter](https://github.com/curlconverter/curlconverter)

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by sharevb** [comment]
Hi @GitCourser, implemented in PR #1171

**Comment by GitCourser** [comment]
Thank you, I searched for the problem of `curl command` in `issues` before and saw that no one mentioned it. It turns out that there is already
