### ISSUE TITLE
it-tools automatically resumes running at system start-up even without enabling docker

### ISSUE THREAD

**Issue by atomwalk12** [CorentinTh/it-tools#1248]
### Describe the bug

The it-tools application keeps automatically restarting whenever I reboot the system.

### What happened?

I installed `it-tools` using the docker image available at `corentinth/it-tools`. However, even after disabling docker, the application keeps restarting automatically when rebooting the system. The application is always available at localhost:8080 even without enabling the docker daemon.

### System information

I tried running 
```
 sudo netstat -tulnp | grep 8080
``` 
to check for applications actively running on port 8080, however no results are retrieved. What can I do?

### Where did you encounter the bug?

Other (installations, docker, etc.)

**Comment by atomwalk12** [comment]
I would be really grateful to get some help with this. Is anyone available?

**Comment by sharevb** [comment]
Hi @atomwalk12, it-tools is a PWA so it is cached, so even without a server, you can access it "offline", see https://connectuc.elevio.help/en/articles/27-managing-progressive-web-apps-chrome-and-edge to remove

**Comment by atomwalk12** [comment]
Hi @sharevb, thanks a lot for trying to help!

When I go to the chrome://apps/ there do appear some applications, however it-tools is not one of them. Is there any other way of removing the app? I am using chrome on Linux.

**Comment by sharevb** [comment]
Hi, ah, PWA but not installable, so probably clear your browser cache

**Comment by sharevb** [comment]
or just do a Ctrl+F5 ?

**Comment by atomwalk12** [comment]
Ctrl+F5 worked. Much appreciated!
