### ISSUE TITLE
[New tool idea] MAC address format

### ISSUE THREAD

**Issue by CWempe** [CorentinTh/it-tools#1253]
### What type of request is this?

New tool idea

### Clear and concise description of the feature you are proposing

A Tool to format and convert different MAC address formats.

Different vendors use different MAC address formats.

Like:

* aa:bb:cc:dd:ee:ff (standard)
* aa-bb-cc-dd-ee-ff (Windows)
* aabb.ccdd.eeff (Cisco)
* aabbccddeeff (no seperator)

I would like to paste any mac address in a text box and get all different formats as output and be able to copy each with a single button click. (similar to date-converter)

### Is their example of this tool in the wild?

I don't know.

### Additional context

This is different from https://github.com/CorentinTh/it-tools/issues/1146

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by sharevb** [comment]
Hi @CWempe, implemented in https://github.com/CorentinTh/it-tools/pull/867

**Comment by CWempe** [comment]
Oh, sorry.

I somehow misunderstood that issue.
Maybe "MAC to generate EUI-64 IPV6 address" confused me.

But it looks like my Issue is a duplicate. 😅

So I will close this and wait for the new tool to be integrated in the collection.
