### ISSUE TITLE
Text Diff module not working when using reverse proxy (with authentik)

### ISSUE THREAD

**Issue by gitmotion** [CorentinTh/it-tools#1291]
### Describe the bug

Text Diff module does not load anymore. Noticed it works if I access from the internal ip but not from the reverse proxy. I've also tried adding it directly to npm with a custom location mapped to the assests folder and container but still gives me the same error.

![image](https://github.com/user-attachments/assets/94f1500a-4dfe-42c3-9658-5b156094762c)

### What happened?

It should load as it does on the internal ip

### System information

- Docker
- Nginx Proxy Manager
- Authentik

### Where did you encounter the bug?

Self hosted

**Comment by Fintanw23** [comment]
Wow exactly my issue and setup! Very annoying as text-diff is 90% of what i use this container for :(

**Comment by gitmotion** [comment]
ah so i'm starting to believe this is a CORS issue, since having an authentication provider like authentik redirects from the authentik URL. got this error this when trying to access my local version vs external version (instead of internal ip)

![image](https://github.com/user-attachments/assets/06764940-955a-4ee4-900a-e65c4d9eddd9)

**Comment by gitmotion** [comment]
looks like the error was happening from dynamically importing the module
![image](https://github.com/user-attachments/assets/15fe409d-af8b-4dfb-9c0b-d9190e97575e)

pr: https://github.com/CorentinTh/it-tools/pull/1352
- imported component directly into text-diff.vue file

**Comment by AlexD0TNET** [comment]
@gitmotion I ran into the same problem, and while adding /assets/* to the Unauthenticated Paths does fix this issue, it seems to also pretty much disable authentication.
Try opening your it-tools like this, from a browser which is not logged into authentik: https://<DOMAIN>/assets/test

When I tested it, it showed me a 404 (because /assets/test does not exist) but completely bypassed the forward authentication via authentik. From this 404 screen you are able to use it-tools freely, as long as you don't refresh the page.

**Comment by gitmotion** [comment]
@AlexD0TNET @Loigzorn interesting 🤔 i already have caching off on my NPM but the issue does seem related to caching within it-tools from my own experience. my setup might be a little different because i just created one main entrypoint to authentik, instead of creating separate proxy hosts for each service and then let authentik handle the rest. but in theory i believe it should be the same underlying issue.
![Image](https://github.com/user-attachments/assets/28289157-d78a-4041-91ab-00ee39489113)

i've kinda come to understand that it might be because it-tools is presenting the cached version the first time but without authentik actually authenticated (or expired auth) so it can't access "/assets". so it looks like you should be able to access the tool but in reality you should be seeing the authentik screen on first load instead.

i haven't had the time to find an actual fix for this also partly because i think it's related to the caching nature of it-tools (since it's meant to work without an internet connection if you already accessed it before, for IT issues) which somewhat conflicts with the nature of exposing it with authentik per se.

however there was a potential workaround i found recently that works for me (**without unauthenticated paths**) which kinda sounds similar to @Loigzorn's workaround
- hard reload the page if text-diff wasn't working (ctrl+shift+r / cmd+shift+r).
- this would trigger authentik and then after authenticating you would be presented with the 404 screen. 
- hard reload again **while** on the 404 screen text diff page should load/work again. (hard reloading again was the key difference for me lol)

not the best workaround but it's a middle ground between getting it to work without changing the caching nature of IT-Tools, and securing it without unauthenticated paths. i don't use the text-diff tool super often so this workaround is fine for me for only when i need it.

**Comment by gitmotion** [comment]
> When I tested it, it showed me a 404 (because /assets/test does not exist) but completely bypassed the forward authentication via authentik. From this 404 screen you are able to use it-tools freely, as long as you don't refresh the page.

this actually sounds more like the built-in caching at play. but yeah rather not set the unauthenticated paths if possible
