### ISSUE TITLE
Replace Twitter-Link with X

### ISSUE THREAD

**Issue by CWempe** [CorentinTh/it-tools#1344]
### Describe the bug

Just a small notice.

On the upper right corner there is a Link to the ittoolsdottech-Twitter-Account.
I think needs to be renamed to X, eventually. 😉 

### What happened?

nothing

### System information

irrelevant

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by gitmotion** [comment]
@CWempe added in: https://github.com/CorentinTh/it-tools/pull/1369
