### ISSUE TITLE
I uninstalled it tools installation, but still have access. May I ask why?? Is there a virus???

### ISSUE THREAD

**Issue by zxuanhong** [CorentinTh/it-tools#1345]
### Describe the bug

1. I uninstalled it tools installation, but still have access. May I ask why?? Is there a virus???
2. I have cleared the browser cache
3. The query port has no 8080 port in use
4. May I ask why access is still available
5. How can I uninstall it thoroughly
6. video info

https://github.com/user-attachments/assets/602a3ae5-c997-4a1a-93eb-75cfb853e943

7. Chrome has been accessed and can be accessed no matter how it is uninstalled. Safari has not been accessed and cannot be accessed after uninstallation
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/680bee25-0915-455e-83b2-1293d1449756">

8. I have reason to suspect the presence of a virus

### What happened?

A bug happened!

### System information

envinfo@7.14.0

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by sak96** [comment]
Faced similar issue. The cause was browser caching, clearing cache and cookie for the site actually fixed it.
