### ISSUE TITLE
favorite action not work in chinese lang

### ISSUE THREAD

**Issue by lezhizhe** [CorentinTh/it-tools#1358]
### Describe the bug

Fist, When selecting Chinese language, when clicking the favorite icon on the detail page, it doesn't work.
<img width="1644" alt="image" src="https://github.com/user-attachments/assets/3bcae347-8827-4e9d-833f-7bba85a1dd1a">

Second, When I have favorited  a number of
 tools in the English environment and then switch to Chinese, it also has no effect.

<img width="840" alt="image" src="https://github.com/user-attachments/assets/8646320e-dc27-4f83-ad29-8fb32e7fd719">
After switch to Chinese，only one tools in my favorite list. that one I favorite on home page.
<img width="834" alt="image" src="https://github.com/user-attachments/assets/779a7e4e-a607-4b77-aca3-52ae8b740adf">

### System information

Chrome 版本 129.0.6668.101（正式版本） (arm64)

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by sharevb** [comment]
Hi @lezhizhe, fixed in https://github.com/CorentinTh/it-tools/pull/1202
