### ISSUE TITLE
Favorite Button Not working on a tool

### ISSUE THREAD

**Issue by clintonleroux** [CorentinTh/it-tools#1365]
### Describe the bug

When on a tool, the favorite button is not working. I plan to submit a PR

### What happened?

When clicking the favorite button it is not adding to favorite (on a tool only not on home page)

### System information

System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 5.18 GB / 15.82 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527

### Where did you encounter the bug?

Other (installations, docker, etc.)

**Comment by gitmotion** [comment]
@clintonleroux @CorentinTh added fix here: https://github.com/CorentinTh/it-tools/pull/1368

**Comment by gitmotion** [comment]
**- previously was not passing the route path to the object when passing as tool:**
![toollayoutonlypassesname](https://github.com/user-attachments/assets/28f58762-c872-4cef-bd3f-dd3bd66a01cf)
![frompageonlypassesname](https://github.com/user-attachments/assets/fac6d254-4abf-4b18-9fc2-f8cc8ed450d6)

**- this also caused it to add nulls to the favoritesToolName in local storage:**
![addsnull](https://github.com/user-attachments/assets/2c44e408-fa7d-448b-8b59-61a76b6742aa)

**- adding the path should prevent nulls from getting add now but also added if check before adding directly to the store:**
![after change](https://github.com/user-attachments/assets/e57d66a3-ce32-43ec-b473-d789b3e7f44b)
