### ISSUE TITLE
Magnet link and torrent file generator

### ISSUE THREAD

**Issue by Retract1822** [CorentinTh/it-tools#1392]
### What type of request is this?

New tool idea

### Clear and concise description of the feature you are proposing

It would be awesome if we can have a Magnet link generator where you can input a torrent info hash and torrent name and it will generate a magnet link for it along with an optional .torrent file for download. 

For example the hash for the current Arch Linux ISO is: 186e418c3db64cf184f505ef85d4fa30928e6252 and the magnet link would look something like this:

magnet:?xt=urn:btih:186e418c3db64cf184f505ef85d4fa30928e6252&dn=archlinux-2024.11.01-x86_64.iso

where `dn` is the torrent name

### Is their example of this tool in the wild?

Closest I could find is here: https://hardrisk.github.io/magnet/ but it doesn't generate a .torrent file to download nor is it self-hosted

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature can be implemented in a client side only app (IT-Tools is client side only, no server).

**Comment by sharevb** [comment]
Hi @Retract1822, implemented in #1201

**Comment by sharevb** [comment]
Hi, for people interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

**Comment by Retract1822** [comment]
> Hi @Retract1822, implemented in #1201

Thank you so much! I didn't think it was that important which is why I tried to close it, but thank you :)

> Hi, for people interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

Out of interest what's more up to date about it - I noticed it mentions adding all the PRs. Does this mean the original IT-Tools (i.e this repo) is no longer being developed? Also do you expect the fork to be kept in sync/up to date with new features added to this repo? I'm wondering which one I should use going forward, as I'd like to stick with the one that's being kept up to date and is seeing active development.

Thanks again

**Comment by sharevb** [comment]
Hi @Retract1822, my idea about this "temporary" fork (I would hope sometime, PR will be merged by @CorentinTh, the only maintainer of this repo as far as I know), I forked : 
1/ because I made many "not yet merged PR since months" (https://github.com/CorentinTh/it-tools/pulls/sharevb)
2/ because many people asked about up to date PR (and some of the tools are useful to me)
3/ PR previews are no longer deployed

I will always make PR on the original repo and bulkly apply them to my fork. BUT for time being, I don't actually care about any other translation than english.
So, I call my fork "temporary"

**Comment by Retract1822** [comment]
That makes sense, thank you for all your hard work. I do hope all the PRs get more attention, you've certainly put in a lot of effort :)
