### ISSUE TITLE
License stated on /about does not align with respository license

### ISSUE THREAD

**Issue by mark-pitblado** [CorentinTh/it-tools#1406]
### Describe the bug

On `/about` the following sentence implies that the repository is under the MIT license, whereas, to the best of my understanding, the repository is actually under the GPL-3.0 License

> IT Tools is open-source (under the MIT license) and free, and will always be, but it costs me money to host and renew the domain name.

### What happened?

N/A

### System information

N/A

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by CorentinTh** [comment]
Hello @mark-pitblado 
Yeah you're right, I'll update the one in the `/about`, thanks for finding out
