### ISSUE TITLE
Regex Tester works failed

### ISSUE THREAD

**Issue by yuf19-2022** [CorentinTh/it-tools#1429]
### Describe the bug

![image](https://github.com/user-attachments/assets/6aa85f0d-c754-4c44-a954-afc211b077c0)
https://any86.github.io/any-rule/
![image](https://github.com/user-attachments/assets/d9f98fa4-45f6-45af-9a0a-8794b47af747)

### What happened?

Regex Tester works failed

### System information

no

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by sharevb** [comment]
Hi @yuf19-2022 , as we are mostly non chinese readers and for faster answering, please provide input and regex in text form (and not only screenshots), thanks.

**Comment by sharevb** [comment]
Hi @yuf19-2022 , corrected here : https://sharevb-it-tools.vercel.app/regex-tester and un PR #1391

**Comment by sharevb** [comment]
Hi @yuf19-2022 , I made a fork here : https://github.com/sharevb/it-tools
