### ISSUE TITLE
[FEAT] Use Volta to manage node and npm/yarn versions

### ISSUE THREAD

**Issue by frode** [CorentinTh/it-tools#246]
**Is your feature request related to a problem? Please describe.**
- nvm is unstable with the latest builds for windows, and the last stable windows version is almost 4 years old.
- nvm does not automatically switch to the correct versions based on the project/git repo.

**Describe the solution you'd like**
- [Volta](https://volta.sh/)
- Volta manages the node and npm/yarn version in package.json
- Volta automatically switches to the correct version based on versions defined in package.json

**Describe alternatives you've considered**
- None that I know of

**Additional context**
- Makes development a little less hassle across linux/mac/win
- Takes just a few minutes to setup

**Comment by CorentinTh** [comment]
See #247
