### ISSUE TITLE
[FEAT] Crypto > HMAC Generator

### ISSUE THREAD

**Issue by marvin-j97** [CorentinTh/it-tools#250]
A HMAC is kinda like a regular hash but with an additional secret.

https://en.wikipedia.org/wiki/HMAC

**Comment by CorentinTh** [comment]
Good idea 👌🏻 
I'll make that

**Comment by CorentinTh** [comment]
It's live: https://it-tools.tech/hmac-generator 😄 

![screely-1659541276254](https://user-images.githubusercontent.com/25065347/182654396-1a24fd63-1eed-4b3f-b6d4-b707d894dd2a.png)
