### ISSUE TITLE
[FEAT] Crypto > Allow base64 digest

### ISSUE THREAD

**Issue by marvin-j97** [CorentinTh/it-tools#251]
Currently the `hash-text` tool is outputting hex strings, but hashes could also be output as base64-encoded strings (or even binary data technically).

(Add select box to select digest encoding)

Also consider for #250

**Comment by CorentinTh** [comment]
Good point, I'll make a dropdown selector for the output type 👌🏻

**Comment by CorentinTh** [comment]
Done!

It's live: https://it-tools.tech/hash-text

![screely-1659541361248](https://user-images.githubusercontent.com/25065347/182654194-f9ce0d68-83fb-432a-bb69-0f7a360b8f88.png)
