### ISSUE TITLE
SVG Image Placeholder

### ISSUE THREAD

**Issue by Yohn** [CorentinTh/it-tools#253]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Something like the following would be good - https://codepen.io/andreasnylin/full/PgGxQv

**Describe alternatives you've considered**
Rather have your site be the all in one place.

**Additional context**
It helps with building out some website and quickly putting an image block where we would expect it.
And it could add onto your base 64 features as well.

**Comment by CorentinTh** [comment]
That's a really good idea for a new tool, thank you for the idea 👌🏻 
I'll make that !

**Comment by CorentinTh** [comment]
It's live! Have a look: https://it-tools.tech/svg-placeholder-generator (force refresh to clear your cache in case of 404)
I was quiet fun to make

![screely-1659541862448](https://user-images.githubusercontent.com/25065347/182652958-75c2ffe4-d8b9-4342-9b7c-4c1b867f52ee.png)

**Comment by Yohn** [comment]
Man that's awesome! And a quick turn around! Heck yeah, Keep up the great work! If I stumble upon something else that would be a good addition, I'll be sure to let you know!

Thanks for adding this. I'll definitely be using it this week

**Comment by CorentinTh** [comment]
Thanks for those kind words! 
Yeah do not hesitate to submit other tool ideas 🙏🏻
