### ISSUE TITLE
Generate OTP codes for Multi-Factor Authentication

### ISSUE THREAD

**Issue by AllDayAlone** [CorentinTh/it-tools#258]
**Is your feature request related to a problem? Please describe.**
MFA is a popular feature, and having a UI to produce OTP codes can be helpful for testing/debugging. 

**Describe the solution you'd like**
There are plenty of libs that provide OTP functionality. For example, https://github.com/yeojz/otplib. It works in the browser. 
There is a website that does precisely this 😄  https://get2fa.dev/ We can copy its look

**Describe alternatives you've considered**
As I said https://get2fa.dev/ or mobile app.

**Comment by CorentinTh** [comment]
Hello @AllDayAlone 

Thank you for the idea, it's indeed a great feature to have on it-tools 👌🏻

I'll set it up ✌🏻

**Comment by CorentinTh** [comment]
Hi!

The OTP generator is live 🎉 

Check it out: https://it-tools.tech/otp-generator

Does it suit your needs?

![screely-1661293275235](https://user-images.githubusercontent.com/25065347/186277663-b07e7a2c-390a-4c2c-9cd9-f1b816efc218.png)

**Comment by AllDayAlone** [comment]
@CorentinTh Thank you! It looks awesome

**Comment by AllDayAlone** [comment]
Just wanted to let you know that I'm using it and having a very good experience. Thank you again! @CorentinTh

**Comment by CorentinTh** [comment]
I'm really glad it meets your needs! Thanks for the feedback ❤️  @AllDayAlone
