### ISSUE TITLE
[FEAT] ObjectID converter

### ISSUE THREAD

**Issue by AllDayAlone** [CorentinTh/it-tools#259]
**Is your feature request related to a problem? Please describe.**
I'm working with MongoDB a lot. Sometimes it's helpful to get a timestamp out of ObjectID.

**Describe the solution you'd like**
Paste ObjectID and see time. Mb add another option in https://it-tools.tech/date-converter

**Describe alternatives you've considered**
https://steveridout.com/mongo-object-time/

**Comment by CorentinTh** [comment]
Thank you for the idea!

It's live : https://it-tools.tech/date-converter

![screely-1662717733673](https://user-images.githubusercontent.com/25065347/189325499-8133b08d-e583-4aa2-b73f-a9867824cb88.png)
