### ISSUE TITLE
Integer base converter not accepting characters

### ISSUE THREAD

**Issue by AndreaSoprani** [CorentinTh/it-tools#263]
When trying to convert a hexadecimal number to other bases, the input field doesn't accept alphabet characters that are part of the hexadecimal digits (a, b, c, d, e and f).
Additionally, the + and - button don't consider these characters, essentially skipping numbers that are accepted in this base.

**To Reproduce**
1. Go to the integer base converter tool (https://it-tools.tech/base-converter)
2. Set 16 as the input base
3. Try to enter any of the alphabet characters that are accepted in the hexadecimal base (e.g. "a")
4. The input is marked as invalid

**Expected behavior**
The converter should accept this hexadecimal number and covert it properly (e.g. "a" base-16 = "10" base-10).

**Screenshots**
![Invalid "a" parsing](https://user-images.githubusercontent.com/9198018/204297241-457bee9d-c60c-4763-acb9-78d5e28eaffb.png)

![Correct "9" parsing](https://user-images.githubusercontent.com/9198018/204297079-ffb5a5dc-66e6-42dd-9c72-2dbf72460730.png)

![Added 1 to "9", going to 0x10 which is 16 instead of 0xa which is 10](https://user-images.githubusercontent.com/9198018/204297363-1df42edf-36ed-4d65-ad2a-e745cbe7d9c0.png)

**Configuration:**
 - Device: Mac
 - OS: MacOS
 - Browser: Safari (but I reproduced it in Chrome too)

**Comment by CorentinTh** [comment]
Thank you for finding and reporting this error, it should now be fixed 👌🏻 
-> https://it-tools.tech/base-converter
