### ISSUE TITLE
[FEAT] Allow tool configuration via url parameters

### ISSUE THREAD

**Issue by Duncank** [CorentinTh/it-tools#264]
**Is your feature request related to a problem? Please describe.**
I'm always trying to save time by automating repetitive tasks, and when using direct links to this site it would be helpful if some settings could be set via the url.

**Describe the solution you'd like**
I'd like to be able to set settings via the url; eg: `https://it-tools.tech/token-generator/?length=32` for a token generator that initiates with a 32-character length by default.

**Additional context**
This would obviously not work for every tool in the site, but for the ones with configuration options it would come in handy.

**Comment by CorentinTh** [comment]
Hello @Duncank 
Thank you for taking to submit this request!
 
That's something I always had in the back of my head, to make the config of tools persistent accross sessions/share/bookmark via query and/or local storage

Since you mention, I'll dive the subject and make it possible 

Thank you!

**Comment by Duncank** [comment]
Nice! Let me know if you can use some help with it, I'm happy to assist!

**Comment by CorentinTh** [comment]
Is this the kind of stuff you had in mind (preview env) : https://dev.it-tools.tech/token-generator ?
(force refresh if needed)

**Comment by Duncank** [comment]
Exactly this! Bonus points for the fact that the url updates when you change some settings manually, that makes for great discovery of this feature 👍

**Comment by revilo951** [comment]
Could this feature be added to tools that have text entry fields, for example the Text to NATO converter? It'd be handy to be able to send someone a link with text pre-filled, ie https://dev.it-tools.tech/text-to-nato-alphabet?input=it-tools.tech
