### ISSUE TITLE
[BUG] case-converter discarding accented letters

### ISSUE THREAD

**Issue by wc-matteo** [CorentinTh/it-tools#266]
**Describe the bug**
accented letters (and possibly other characters) are removed from case-converter's results

**To Reproduce**
https://it-tools.tech/case-converter

![image](https://user-images.githubusercontent.com/10562635/217499379-971a2da8-8228-4044-a197-299c856ecb28.png)

**Expected behavior**
accented letters are not removed and, if needed, are converted to upper/lower case

**Comment by CorentinTh** [comment]
Hi @wc-matteo !
Thanks for the report, I'll fix this 🙏

**Comment by CorentinTh** [comment]
Fixed!
Diacritics are now allowed
https://it-tools.tech/case-converter

![image](https://user-images.githubusercontent.com/25065347/218207158-6892cd42-b247-4cda-9ca3-5f1f3faf94d0.png)
