### ISSUE TITLE
[FEAT] Docker Image

### ISSUE THREAD

**Issue by ItsNoted** [CorentinTh/it-tools#270]
Is there a Dockerfile for this? I'd like to build an image for it if possible.

**Comment by CorentinTh** [comment]
Hi @ItsNoted 
Why would you need a docker image for it-tools ? 🤔 
It's freely accessible everywhere https://it-tools.tech/

**Comment by ItsNoted** [comment]
> Hi @ItsNoted Why would you need a docker image for it-tools ? 🤔 It's freely accessible everywhere https://it-tools.tech/

Why, for self-hosting of course!

**Comment by CorentinTh** [comment]
Okey, I see, I'll make a docker image for it-tools

**Comment by ItsNoted** [comment]
Great. Thank you! Mind if I feature this on Noted website? I think my audience would really like this!

**Comment by ItsNoted** [comment]
I followed it. Thanks again 😊

**Comment by CorentinTh** [comment]
I added the current version on Docker Hub
https://hub.docker.com/r/corentinth/it-tools

You can start your instance with:
```sh
docker run -d -p 8080:80 --name it-tools -it corentinth/it-tools
```

I'll make a github action to auto push the latest version to the hub on new release

**Comment by CorentinTh** [comment]
I did not have in mind for the app to be runnable offline when building, let me know if something is fishy

**Comment by CorentinTh** [comment]
The CD to docker hub is [up and running](https://github.com/CorentinTh/it-tools/blob/main/.github/workflows/docker-release.yml)
the `corentinth/it-tools@latest` docker image will always be up to date with the main branch

**Comment by ItsNoted** [comment]
Excellent. Thank you :)

**Comment by ItsNoted** [comment]
Is there a written list of every tool so I dont have to manually type them all out?

**Comment by CorentinTh** [comment]
If you want the tools details, here is a json with the name, description and path of each tool
```json
[{"name":"Token generator","description":"Generate random string with the chars you want: uppercase or lowercase letters, numbers and/or symbols.","path":"/token-generator"},{"name":"Hash text","description":"Hash a text string using the function you need : MD5, SHA1, SHA256, SHA224, SHA512, SHA384, SHA3 or RIPEMD160","path":"/hash-text"},{"name":"Bcrypt","description":"Hash and compare text string using bcrypt. Bcrypt is a password-hashing function based on the Blowfish cipher.","path":"/bcrypt"},{"name":"UUIDs v4 generator","description":"A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems. The number of possible UUIDs is 16^32, which is 2^128 or about 3.4x10^38 (which is a lot !).","path":"/uuid-generator"},{"name":"Encrypt / decrypt text","description":"Encrypt and decrypt text clear text using crypto algorithm like AES, TripleDES, Rabbit or RC4.","path":"/encryption"},{"name":"BIP39 passphrase generator","description":"Generate BIP39 passphrase from existing or random mnemonic, or get the mnemonic from the passphrase.","path":"/bip39-generator"},{"name":"Hmac generator","description":"Computes a hash-based message authentication code (HMAC) using a secret key and your favorite hashing function.","path":"/hmac-generator"},{"name":"RSA key pair generator","description":"Generate new random RSA private and public key pem certificates.","path":"/rsa-key-pair-generator"},{"name":"Date-time converter","description":"Convert date and time into the various different formats","path":"/date-converter"},{"name":"Integer base converter","description":"Convert number between different bases (decimal, hexadecimal, binary, octal, base64, ...)","path":"/base-converter"},{"name":"Roman numeral converter","description":"Convert Roman numerals to numbers and convert numbers to Roman numerals.","path":"/roman-numeral-converter"},{"name":"Base64 string encoder/decoder","description":"Simply encode and decode string into a their base64 representation.","path":"/base64-string-converter"},{"name":"Base64 file converter","description":"Convert string, files or images into a it's base64 representation.","path":"/base64-file-converter"},{"name":"Color converter","description":"Convert color between the different formats (hex, rgb, hsl and css name)","path":"/color-converter"},{"name":"Case converter","description":"Change the case of a string and chose between different formats","path":"/case-converter"},{"name":"Text to NATO alphabet","description":"Transform text into NATO phonetic alphabet for oral transmission.","path":"/text-to-nato-alphabet"},{"name":"Encode/decode url formatted strings","description":"Encode to url-encoded format (also known as \"percent-encoded\") or decode from it.","path":"/url-encoder"},{"name":"Escape html entities","description":"Escape or unescape html entities (replace <,>, &, \" and ' to their html version)","path":"/html-entities"},{"name":"Url parser","description":"Parse an url string to get all the different parts (protocol, origin, params, port, username-password, ...)","path":"/url-parser"},{"name":"Device information","description":"Get information about your current device (screen size, pixel-ratio, user agent, ...)","path":"/device-information"},{"name":"Basic auth generator","description":"Generate a base64 basic auth header from an username and a password.","path":"/basic-auth-generator"},{"name":"Open graph meta generator","description":"Generate open-graph and socials html meta tags for your website.","path":"/og-meta-generator"},{"name":"OTP code generator","description":"Generate and validate time-based OTP (one time password) for multi-factor authentication.","path":"/otp-generator"},{"name":"Mime types","description":"Convert mime types to extensions and vice-versa.","path":"/mime-types"},{"name":"JWT parser","description":"Parse and decode your JSON Web Token (jwt) and display its content.","path":"/jwt-parser"},{"name":"Keycode info","description":"Find the javascript keycode, code, location and modifiers of any pressed key.","path":"/keycode-info"},{"name":"Slugify string","description":"Make a string url, filename and id safe.","path":"/slugify-string"},{"name":"QR Code generator","description":"Generate and download QR-code for an url or just a text and customize the background and foreground colors.","path":"/qrcode-generator"},{"name":"SVG placeholder generator","description":"Generate svg images to use as placeholder in your applications.","path":"/svg-placeholder-generator"},{"name":"Git cheatsheet","description":"Git is a decentralized version management software. With this cheatsheet you will have a quick access to the most common git commands.","path":"/git-memo"},{"name":"Random port generator","description":"Generate random port numbers outside of the range of \"known\" ports (0-1023).","path":"/random-port-generator"},{"name":"Crontab generator","description":"Validate and generate crontab and get the human readable description of the cron schedule.","path":"/crontab-generator"},{"name":"JSON prettify and format","description":"Prettify your JSON string to a human friendly readable format.","path":"/json-prettify"},{"name":"JSON minify","description":"Minify and compress your JSON by removing unnecessary white spaces.","path":"/json-minify"},{"name":"SQL prettify and format","description":"Format and prettify your SQL queries online (it supports various SQL dialects).","path":"/sql-prettify"},{"name":"Chmod calculator","description":"Compute your chmod permissions and commands with this online chmod calculator.","path":"/chmod-calculator"},{"name":"Math evaluator","description":"Evaluate math expression, like a calculator on steroid (you can use function like sqrt, cos, sin, abs, ...)","path":"/math-evaluator"},{"name":"ETA calculator","description":"An ETA (Estimated Time of Arrival) calculator to know the approximate end time of a task, for example the moment of ending of a download.","path":"/eta-calculator"},{"name":"Chronometer","description":"Monitor the duration of a thing. Basically a chronometer with simple chronometer features.","path":"/chronometer"},{"name":"Temperature converter","description":"Temperature degrees conversions for Kelvin, Celsius, Fahrenheit, Rankine, Delisle, Newton, Réaumur and Rømer.","path":"/temperature-converter"},{"name":"Lorem ipsum generator","description":"Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content","path":"/lorem-ipsum-generator"},{"name":"Text statistics","description":"Get information about a text, the amount of characters, the amount of words, it's size, ...","path":"/text-statistics"}]
```

If you just need the names of the 42 current tools, here they are :

```txt
Token generator
Hash text
Bcrypt
UUIDs v4 generator
Encrypt / decrypt text
BIP39 passphrase generator
Hmac generator
RSA key pair generator
Date-time converter
Integer base converter
Roman numeral converter
Base64 string encoder/decoder
Base64 file converter
Color converter
Case converter
Text to NATO alphabet
Encode/decode url formatted strings
Escape html entities
Url parser
Device information
Basic auth generator
Open graph meta generator
OTP code generator
Mime types
JWT parser
Keycode info
Slugify string
QR Code generator
SVG placeholder generator
Git cheatsheet
Random port generator
Crontab generator
JSON prettify and format
JSON minify
SQL prettify and format
Chmod calculator
Math evaluator
ETA calculator
Chronometer
Temperature converter
Lorem ipsum generator
Text statistics
```

**Comment by CorentinTh** [comment]
Thank you very much @ItsNoted for your article 🙏🏻

**Comment by ItsNoted** [comment]
> Thank you very much @ItsNoted for your article 🙏🏻

I just noticed all the feature requests since I wrote the article. I hope it’s not overwhelming you! Thanks again for your quick response on the docker image!

**Comment by ItsNoted** [comment]
> If you want the tools details, here is a json with the name, description and path of each tool
> 
> ```json
> [{"name":"Token generator","description":"Generate random string with the chars you want: uppercase or lowercase letters, numbers and/or symbols.","path":"/token-generator"},{"name":"Hash text","description":"Hash a text string using the function you need : MD5, SHA1, SHA256, SHA224, SHA512, SHA384, SHA3 or RIPEMD160","path":"/hash-text"},{"name":"Bcrypt","description":"Hash and compare text string using bcrypt. Bcrypt is a password-hashing function based on the Blowfish cipher.","path":"/bcrypt"},{"name":"UUIDs v4 generator","description":"A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems. The number of possible UUIDs is 16^32, which is 2^128 or about 3.4x10^38 (which is a lot !).","path":"/uuid-generator"},{"name":"Encrypt / decrypt text","description":"Encrypt and decrypt text clear text using crypto algorithm like AES, TripleDES, Rabbit or RC4.","path":"/encryption"},{"name":"BIP39 passphrase generator","description":"Generate BIP39 passphrase from existing or random mnemonic, or get the mnemonic from the passphrase.","path":"/bip39-generator"},{"name":"Hmac generator","description":"Computes a hash-based message authentication code (HMAC) using a secret key and your favorite hashing function.","path":"/hmac-generator"},{"name":"RSA key pair generator","description":"Generate new random RSA private and public key pem certificates.","path":"/rsa-key-pair-generator"},{"name":"Date-time converter","description":"Convert date and time into the various different formats","path":"/date-converter"},{"name":"Integer base converter","description":"Convert number between different bases (decimal, hexadecimal, binary, octal, base64, ...)","path":"/base-converter"},{"name":"Roman numeral converter","description":"Convert Roman numerals to numbers and convert numbers to Roman numerals.","path":"/roman-numeral-converter"},{"name":"Base64 string encoder/decoder","description":"Simply encode and decode string into a their base64 representation.","path":"/base64-string-converter"},{"name":"Base64 file converter","description":"Convert string, files or images into a it's base64 representation.","path":"/base64-file-converter"},{"name":"Color converter","description":"Convert color between the different formats (hex, rgb, hsl and css name)","path":"/color-converter"},{"name":"Case converter","description":"Change the case of a string and chose between different formats","path":"/case-converter"},{"name":"Text to NATO alphabet","description":"Transform text into NATO phonetic alphabet for oral transmission.","path":"/text-to-nato-alphabet"},{"name":"Encode/decode url formatted strings","description":"Encode to url-encoded format (also known as \"percent-encoded\") or decode from it.","path":"/url-encoder"},{"name":"Escape html entities","description":"Escape or unescape html entities (replace <,>, &, \" and ' to their html version)","path":"/html-entities"},{"name":"Url parser","description":"Parse an url string to get all the different parts (protocol, origin, params, port, username-password, ...)","path":"/url-parser"},{"name":"Device information","description":"Get information about your current device (screen size, pixel-ratio, user agent, ...)","path":"/device-information"},{"name":"Basic auth generator","description":"Generate a base64 basic auth header from an username and a password.","path":"/basic-auth-generator"},{"name":"Open graph meta generator","description":"Generate open-graph and socials html meta tags for your website.","path":"/og-meta-generator"},{"name":"OTP code generator","description":"Generate and validate time-based OTP (one time password) for multi-factor authentication.","path":"/otp-generator"},{"name":"Mime types","description":"Convert mime types to extensions and vice-versa.","path":"/mime-types"},{"name":"JWT parser","description":"Parse and decode your JSON Web Token (jwt) and display its content.","path":"/jwt-parser"},{"name":"Keycode info","description":"Find the javascript keycode, code, location and modifiers of any pressed key.","path":"/keycode-info"},{"name":"Slugify string","description":"Make a string url, filename and id safe.","path":"/slugify-string"},{"name":"QR Code generator","description":"Generate and download QR-code for an url or just a text and customize the background and foreground colors.","path":"/qrcode-generator"},{"name":"SVG placeholder generator","description":"Generate svg images to use as placeholder in your applications.","path":"/svg-placeholder-generator"},{"name":"Git cheatsheet","description":"Git is a decentralized version management software. With this cheatsheet you will have a quick access to the most common git commands.","path":"/git-memo"},{"name":"Random port generator","description":"Generate random port numbers outside of the range of \"known\" ports (0-1023).","path":"/random-port-generator"},{"name":"Crontab generator","description":"Validate and generate crontab and get the human readable description of the cron schedule.","path":"/crontab-generator"},{"name":"JSON prettify and format","description":"Prettify your JSON string to a human friendly readable format.","path":"/json-prettify"},{"name":"JSON minify","description":"Minify and compress your JSON by removing unnecessary white spaces.","path":"/json-minify"},{"name":"SQL prettify and format","description":"Format and prettify your SQL queries online (it supports various SQL dialects).","path":"/sql-prettify"},{"name":"Chmod calculator","description":"Compute your chmod permissions and commands with this online chmod calculator.","path":"/chmod-calculator"},{"name":"Math evaluator","description":"Evaluate math expression, like a calculator on steroid (you can use function like sqrt, cos, sin, abs, ...)","path":"/math-evaluator"},{"name":"ETA calculator","description":"An ETA (Estimated Time of Arrival) calculator to know the approximate end time of a task, for example the moment of ending of a download.","path":"/eta-calculator"},{"name":"Chronometer","description":"Monitor the duration of a thing. Basically a chronometer with simple chronometer features.","path":"/chronometer"},{"name":"Temperature converter","description":"Temperature degrees conversions for Kelvin, Celsius, Fahrenheit, Rankine, Delisle, Newton, Réaumur and Rømer.","path":"/temperature-converter"},{"name":"Lorem ipsum generator","description":"Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content","path":"/lorem-ipsum-generator"},{"name":"Text statistics","description":"Get information about a text, the amount of characters, the amount of words, it's size, ...","path":"/text-statistics"}]
> ```
> 
> If you just need the names of the 42 current tools, here they are :
> 
> ```
> Token generator
> Hash text
> Bcrypt
> UUIDs v4 generator
> Encrypt / decrypt text
> BIP39 passphrase generator
> Hmac generator
> RSA key pair generator
> Date-time converter
> Integer base converter
> Roman numeral converter
> Base64 string encoder/decoder
> Base64 file converter
> Color converter
> Case converter
> Text to NATO alphabet
> Encode/decode url formatted strings
> Escape html entities
> Url parser
> Device information
> Basic auth generator
> Open graph meta generator
> OTP code generator
> Mime types
> JWT parser
> Keycode info
> Slugify string
> QR Code generator
> SVG placeholder generator
> Git cheatsheet
> Random port generator
> Crontab generator
> JSON prettify and format
> JSON minify
> SQL prettify and format
> Chmod calculator
> Math evaluator
> ETA calculator
> Chronometer
> Temperature converter
> Lorem ipsum generator
> Text statistics
> ```

Thanks @CorentinTh! I am updating my article today. Loving all the new updates since i wrote it last year. What is the current number of tools today? And how can I find this out for myself without counting them all manually? :D

**Comment by CorentinTh** [comment]
Hi @ItsNoted 
Thank you for the follow up !
They are 71 tools currently 💪🏻 

You can easily get the list off all the tool names by pasting this snippet in the console of it-tools :

```javascript
[...document.querySelectorAll('.sider-content .n-menu-item-content-header a')].map(el => el.innerText)

// Or this one to get the names in your clipboard
copy([...document.querySelectorAll('.sider-content .n-menu-item-content-header a')].map(el => el.innerText).join('\n'))
```

<details>
  <summary>The tool names:</summary>

```
Token generator
Hash text
Bcrypt
UUIDs v4 generator
Encrypt / decrypt text
BIP39 passphrase generator
Hmac generator
RSA key pair generator
Password strength analyser
Date-time converter
Integer base converter
Roman numeral converter
Base64 string encoder/decoder
Base64 file converter
Color converter
Case converter
Text to NATO alphabet
YAML to JSON converter
YAML to TOML
JSON to YAML converter
JSON to TOML
List converter
TOML to JSON
TOML to YAML
Encode/decode url formatted strings
Escape html entities
Url parser
Device information
Basic auth generator
Open graph meta generator
OTP code generator
Mime types
JWT parser
Keycode info
Slugify string
HTML WYSIWYG editor
User-agent parser
HTTP status codes
JSON diff
QR Code generator
WiFi QR Code generator
SVG placeholder generator
Camera recorder
Git cheatsheet
Random port generator
Crontab generator
JSON prettify and format
JSON minify
JSON to CSV
SQL prettify and format
Chmod calculator
Docker run to Docker compose converter
XML formatter
IPv4 subnet calculator
Ipv4 address converter
IPv4 range expander
MAC address lookup
IPv6 ULA generator
Math evaluator
ETA calculator
Percentage calculator
Chronometer
Temperature converter
Benchmark builder
Lorem ipsum generator
Text statistics
Emoji picker
String obfuscator
Text diff
Phone parser and formatter
IBAN validator and parser
```
</details>


<details>
  <summary>The url of each tool :</summary>
  
  ```
https://it-tools.tech/token-generator
https://it-tools.tech/hash-text
https://it-tools.tech/bcrypt
https://it-tools.tech/uuid-generator
https://it-tools.tech/encryption
https://it-tools.tech/bip39-generator
https://it-tools.tech/hmac-generator
https://it-tools.tech/rsa-key-pair-generator
https://it-tools.tech/password-strength-analyser
https://it-tools.tech/date-converter
https://it-tools.tech/base-converter
https://it-tools.tech/roman-numeral-converter
https://it-tools.tech/base64-string-converter
https://it-tools.tech/base64-file-converter
https://it-tools.tech/color-converter
https://it-tools.tech/case-converter
https://it-tools.tech/text-to-nato-alphabet
https://it-tools.tech/yaml-to-json-converter
https://it-tools.tech/yaml-to-toml
https://it-tools.tech/json-to-yaml-converter
https://it-tools.tech/json-to-toml
https://it-tools.tech/list-converter
https://it-tools.tech/toml-to-json
https://it-tools.tech/toml-to-yaml
https://it-tools.tech/url-encoder
https://it-tools.tech/html-entities
https://it-tools.tech/url-parser
https://it-tools.tech/device-information
https://it-tools.tech/basic-auth-generator
https://it-tools.tech/og-meta-generator
https://it-tools.tech/otp-generator
https://it-tools.tech/mime-types
https://it-tools.tech/jwt-parser
https://it-tools.tech/keycode-info
https://it-tools.tech/slugify-string
https://it-tools.tech/html-wysiwyg-editor
https://it-tools.tech/user-agent-parser
https://it-tools.tech/http-status-codes
https://it-tools.tech/json-diff
https://it-tools.tech/qrcode-generator
https://it-tools.tech/wifi-qrcode-generator
https://it-tools.tech/svg-placeholder-generator
https://it-tools.tech/camera-recorder
https://it-tools.tech/git-memo
https://it-tools.tech/random-port-generator
https://it-tools.tech/crontab-generator
https://it-tools.tech/json-prettify
https://it-tools.tech/json-minify
https://it-tools.tech/json-to-csv
https://it-tools.tech/sql-prettify
https://it-tools.tech/chmod-calculator
https://it-tools.tech/docker-run-to-docker-compose-converter
https://it-tools.tech/xml-formatter
https://it-tools.tech/ipv4-subnet-calculator
https://it-tools.tech/ipv4-address-converter
https://it-tools.tech/ipv4-range-expander
https://it-tools.tech/mac-address-lookup
https://it-tools.tech/ipv6-ula-generator
https://it-tools.tech/math-evaluator
https://it-tools.tech/eta-calculator
https://it-tools.tech/percentage-calculator
https://it-tools.tech/chronometer
https://it-tools.tech/temperature-converter
https://it-tools.tech/benchmark-builder
https://it-tools.tech/lorem-ipsum-generator
https://it-tools.tech/text-statistics
https://it-tools.tech/emoji-picker
https://it-tools.tech/string-obfuscator
https://it-tools.tech/text-diff
https://it-tools.tech/phone-parser-and-formatter
https://it-tools.tech/iban-validator-and-parser
  ```
</details>
