### ISSUE TITLE
[FEAT] New tool: Docker Compose to Docker Run and vice-versa

### ISSUE THREAD

**Issue by rursache** [CorentinTh/it-tools#276]
## Describe the solution you'd like
Would be nice to include [this](https://8gwifi.org/dc2.jsp) great tool that converts Docker Compose yaml to a simple Docker Run command. 

~~There is also the option to convert Docker Run to Docker Compose~~ 
seems run -> composer got implemented, composer -> run would be nice next

**Comment by sonofwatt** [comment]
Tested out this tool using the it-tools run command "docker run -d -p 8080:80 --name it-tools -it corentinth/it-tools"
The output looks good except shows "image: run".

**Comment by rursache** [comment]
> Tested out this tool using the it-tools run command "docker run -d -p 8080:80 --name it-tools -it corentinth/it-tools"
> 
> The output has a few issues, including the image source being listed as run "image: run".

this is unrelated to the current issue. read the docker documentation and learn to use docker first. remove the '-it' param

**Comment by ngosang** [comment]
I have been using the tool in https://it-tools.tech/docker-run-to-docker-compose-converter
It will possible to do the reverse conversion in the future? docker-compose => docker run

**Comment by SiJiL82** [comment]
> > Tested out this tool using the it-tools run command "docker run -d -p 8080:80 --name it-tools -it corentinth/it-tools"
> > The output has a few issues, including the image source being listed as run "image: run".
> 
> this is unrelated to the current issue. read the docker documentation and learn to use docker first. remove the '-it' param

The command they've used is directly from the readme for this project - I don't think it's unreasonable for someone to paste that into the tool to try it out without "learning to use docker first"...

**Comment by rursache** [comment]
> @SiJiL82 The command they've used is directly from the readme for this project - I don't think it's unreasonable for someone to paste that into the tool to try it out without "learning to use docker first"...

I created a pull request to fix the command for all of you copy-pasting code from the internet without understanding it first. Also this issue is not about this, it's about a tool inside the project.
https://github.com/CorentinTh/it-tools/pull/323

**Comment by CorentinTh** [comment]
I've started fixing the generation of the docker compose, I'm rebuilding a more modern composerize

**Comment by cgoIT** [comment]
Hi, I worked in this too. I can give you a link when I‘m at home.

**Comment by cgoIT** [comment]
Hi @CorentinTh,

I first wanted to fix the currently used tool but then ended in developing a new one. You can find the new tool [here](https://github.com/cgoIT/composerize-ts).
Any feedback is highly appreciated.

Cheers,
Carsten

**Comment by rursache** [comment]
great job @cgoIT but there are already multiple tools to convert docker run to compose. anyone willing to build a compose to run? i prefer commands instead of files so i use docker run

**Comment by sonofwatt** [comment]
> this is unrelated to the current issue. read the docker documentation and learn to use docker first. remove the '-it' param
I just grabbed the example run command from the readme to test it out. 
Shouldn't a well made compose generator filter out invalid params?

**Comment by rursache** [comment]
@sonofwatt you still don't understand that this issue is a feature request, if you have problems with a tool, create a separate issue. also the example docker run and this converter tool has nothing to do with each other and this specific feature request.

i'll close this issue as the docker run -> composer tool was implemented. if anyone want to implement the composer -> run converter as well, i'll be grateful
