### ISSUE TITLE
[FEAT] TinyMCE Editor

### ISSUE THREAD

**Issue by TCB13** [CorentinTh/it-tools#277]
Hello,

Thank you for the great set of tool and nice UI it has. 

I would like to request the TinyMCE editor to be added to the Web Tools. Sometimes it's useful to be able to quickly format some text with a WYSIWYG editor and output the HTML.

Thank you.

**Comment by CorentinTh** [comment]
Done 💪🏻 
Very lightweight for now, I'll iterate to add more buttons, like table support

https://it-tools.tech/html-wysiwyg-editor

![screely-1679854909286](https://user-images.githubusercontent.com/25065347/227796150-3b5802bc-feb5-476c-8334-e436ae5c260d.png)

**Comment by CorentinTh** [comment]
Thank you for your request @TCB13

**Comment by TCB13** [comment]
Thank you for including this @CorentinTh !

It also has a menu that can be toggled to have more options, one of them is `View > Source code` that allows the user to edit the HTML directly. This is handy because it also makes it possible to drop a bunch of existing HTML into TinyMCE and revert it to a WYSIWYG editor.

I usually go with this config:

````
tinymce.init({
        selector: "textarea",
        height: 800,
        menubar: true,
        plugins: [
            "advlist autolink lists link image charmap anchor",
            "searchreplace code",
            "table paste code help wordcount"
        ],
        toolbar: "undo redo | formatselect | " +
            "bold italic backcolor | alignleft aligncenter " +
            "alignright alignjustify | bullist numlist outdent indent | " +
            "removeformat | help",
        content_style: "body { font-family:Helvetica,Arial,sans-serif; font-size:14px }"
    });
````
This will give me a very complete editor, example here: https://tcb13.com/demo/mce/
