### ISSUE TITLE
[FEAT] Pre-Compiled Releases

### ISSUE THREAD

**Issue by TCB13** [CorentinTh/it-tools#278]
Hello,

The entirety of this great tool-set runs in HTML/JS so why can't we have pre-compiled releases for people who don't want to make thing harder than they need to be? :) Drop in any webserver and use it.

Thank you.

**Comment by CorentinTh** [comment]
Hi @TCB13 
You mean like a zip with all the raw html/js/css app ?

If one needs this they could just clone and npm run build ?

**Comment by anantshri** [comment]
a npm run build needs the whole npm setup. not everyone would be in that position to build and use it that way. this could be  far more useful for people if there is a simpler way to just copy a zip and deploy it on server. or just double click and use it from a folder.

**Comment by TCB13** [comment]
@CorentinTh yes, releases should be compiled like many other projects. As @anantshri explained most people want to deal with npm.

**Comment by CorentinTh** [comment]
Precompiled release are now a thing with the new release system, you can find a zip in the auto releases 

https://github.com/CorentinTh/it-tools/releases/tag/v2023.4.14-dbad773
