### ISSUE TITLE
[FEAT] Networking Tools

### ISSUE THREAD

**Issue by TCB13** [CorentinTh/it-tools#279]
Hey,

Me again! A section of tools dedicated to networking would be great.

As a start, I've copied, edited and perfected an "IP Range Expander" and a Subnet Calculator and hosted them here https://tcb13.com/demo/subnet/

Would you approve the integration of those tools after a proper code cleanup?

Thank you.

**Comment by cgoIT** [comment]
Maybe https://github.com/rs/node-netmask (Types available here: https://www.npmjs.com/package/@types/netmask) could be an option too.

**Comment by CorentinTh** [comment]
An IPv4 subnet calculator is now out : https://it-tools.tech/ipv4-subnet-calculator


![screely-1680040391904](https://user-images.githubusercontent.com/25065347/228375813-4d81c92c-4078-4c48-89c0-073a44fcd774.png)

**Comment by TCB13** [comment]
@CorentinTh thank you!

What about the range expander, what can I do to make your life easier? The script itself is relatively simple: https://tcb13.com/demo/subnet/iprange.js

**Comment by nzkller** [comment]
@CorentinTh wow congrats, this is amazing! I will open a Feature request for a MAC address lookup that would be pretty handy
