### ISSUE TITLE
[BUG] OTP code generator should accept lower-case secrets

### ISSUE THREAD

**Issue by dimo414** [CorentinTh/it-tools#283]
**Describe the bug**

Secret strings are sometimes provided in lower-case (e.g. Discord does this) - since they're base32 the casing shouldn't matter, but it-tools rejects lower-case strings.

**To Reproduce**
1. Go to 'https://it-tools.tech/otp-generator
2. Type a lower-case base32 string like `abcd`
3. See error "Secret should be a base32 string" and incorrect "Secret in hexadecimal"
4. Swap string to `ABCD`
5; See successful OTP generation

**Expected behavior**

Lower-case secrets should be accepted

**Comment by CorentinTh** [comment]
Thanks for reporting!
Do mean that lowercase characters in secret should be interpreted the same as uppercase ?

**Comment by dimo414** [comment]
Yeah I believe so - I'm just going off the error message saying it's base32, I haven't actually reviewed the spec. But I tried with my Discord code and upper-casing it generates the correct OTP sequence so I think it is supposed to be case-insensitive.

**Comment by CorentinTh** [comment]
Thats fixed !
Thanks again for reporting

https://it-tools.tech/otp-generator

![image](https://user-images.githubusercontent.com/25065347/227803641-9d051bee-01f1-4cec-9dc0-9eca0f689c93.png)

**Comment by CorentinTh** [comment]
btw @dimo414 you are the 1000th star of this repo, thank you very much 🙏🏻

**Comment by dimo414** [comment]
I saw that! It motivated me to star it, tbh 😄
