### ISSUE TITLE
[BUG] Dark mode should not invert QR codes

### ISSUE THREAD

**Issue by dimo414** [CorentinTh/it-tools#284]
**Describe the bug**
QR codes, such as the one displayed on the OTP page, are inverted in dark mode. Although this works with some tools like Google Authenticator (verified manually) [many barcode scanners do not recognize inverted QR codes](http://qrcode.meetheed.com/question2.php), such as [this barcode scanner app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android).

**To Reproduce**
1. Go to https://it-tools.tech/otp-generator
2. Flip between light and dark mode
3. Observe the QR code inverts
4. (Optional) try scanning the barcode with the Barcode Scanner app

**Expected behavior**
The QR code shouldn't change based on the dark mode state.

**Comment by dimo414** [comment]
I notice https://it-tools.tech/qrcode-generator does _not_ do this inversion, so the issue may be limited to the OTP tool.

**Comment by CorentinTh** [comment]
Thank you @dimo414 for reporting this point, it's now fixed
