### ISSUE TITLE
[FEAT] Make sections in sider collapsible and remember state

### ISSUE THREAD

**Issue by juzim** [CorentinTh/it-tools#293]
**Describe the solution you'd like**
Since I don't use some sections at all, I'd like to be able to collapse them. On a reload of the page, the state should persist.

**Describe alternatives you've considered**
Another solution would be to create a "whitelist" mode, where only marked/favorite apps appear in the sidebar.

**Additional context**
I did a test with replacing the div of `n-menu-item-group` with `details` and `n-menu-item-group-title` with `summary`, which worked just fine.

**Comment by CorentinTh** [comment]
Collapsibling categories is now a think !
Thank you for this great idea

Their state is saved in the localstorage

https://it-tools.tech/

![screely-1680213240313](https://user-images.githubusercontent.com/25065347/228972863-7ab921f3-88ae-439f-be8e-602fbd9816ff.png)
