### ISSUE TITLE
[FEAT]Compare strings

### ISSUE THREAD

**Issue by projector22** [CorentinTh/it-tools#294]
**Is your feature request related to a problem? Please describe.**
I regularly need to compare 2 fairly lengthy bodies of text for differences (changes in wording, errant spaces etc.)

**Describe the solution you'd like**
A left and right field into which I would paste each text. The app would then (below I presume) indicate if the texts are identical or not, and highlight any differences found. The highlighting is the most helpful part to my usecase.

**Describe alternatives you've considered**
I have, until now, used [this](https://text-compare.com/) - but I would very much like to have all my tools in one place, and it-tools pretty much covers that, except for this feature.

**Additional context**
-

**Comment by cgoIT** [comment]
@CorentinTh If PR #355 is ok for you maybe the used library jsondiffpatch-rc there could be used for this feature here also. I think the lib is also capable of comparing strings.

**Comment by CorentinTh** [comment]
Done ✅ 
https://it-tools.tech/text-diff

![screely-1693061250172](https://github.com/CorentinTh/it-tools/assets/25065347/0f41e4c4-a4aa-4c87-be12-d6b252f697d5)

**Comment by projector22** [comment]
Beautiful, thank you very much
