### ISSUE TITLE
Docker: Refreshing browser on currently selected tool page results in 404 error[BUG] 

### ISSUE THREAD

**Issue by RobertD502** [CorentinTh/it-tools#297]
**Describe the bug**
Preface: This isn't a critical bug - just something I noticed.

When using any one of the tools, if a user refreshes the page, a 404 page is encountered. Seems to be a configuration that is missing in NGINX for custom locations.

**To Reproduce**
1. Go to the main page for your it-tools docker container(i.e., domain/ip:port)
2. Click on any of the tools
3. Refresh the site in your browser
4. Results in 404 error

**Expected behavior**
Return to the tool currently open with default values presented.

**Screenshots**

**Token generator tool page open:**

![image](https://user-images.githubusercontent.com/52541649/228369231-558c53b9-dca5-4999-8fe7-b5956ee58caa.png)

**Error presented after refreshing current page:**

![image](https://user-images.githubusercontent.com/52541649/228369346-3c315c20-8753-45b8-ae08-79fc33fcd3d5.png)

**Configuration (please complete the following information):**
 - Browser Edge Chromium
 - it-tools version: 2.19.0

**Comment by CorentinTh** [comment]
Thanks for reporting this issue, it's indeed an issue with nginx configuration, I'll fix it

**Comment by CorentinTh** [comment]
The fixing PR is merged, just wait for the new container to be built and pushed to docker hub, and you'll be good to go !
