### ISSUE TITLE
MAC address lookup for networking tools

### ISSUE THREAD

**Issue by nzkller** [CorentinTh/it-tools#300]
**Is your feature request related to a problem? Please describe.**

Is a tools that all IT people use daily when troubleshooting especially in networking and systems. Helps to understand the devices connected to the network and what vendor might be. Is a must in the remote work world we are living now.

**Describe the solution you'd like**
Another tool that will just ask you to enter the MAC address in any format and it will give you the MAC vendor OUI. Like these websites:

- https://maclookup.app
- https://dnschecker.org/mac-lookup.php
- https://aruljohn.com/mac.pl
- https://macaddress.io

**Describe alternatives you've considered**

Beside the websites, the following repos:

- https://github.com/bauerj/mac_vendor_lookup
- https://github.com/MaxAnderson95/MAC-Address-Lookup-Tool
- https://gist.github.com/aallan/b4bb86db86079509e6159810ae9bd3e4

And the closes might be https://github.com/henriksb/MAC-Lookup

But none will be as convenient as yours in the it-tool website

**Comment by CorentinTh** [comment]
It's done !

https://it-tools.tech/mac-adrdress-lookup

![screely-1680819970937](https://user-images.githubusercontent.com/25065347/230505240-e52c35f0-d5b4-4d37-b5e3-099e7bcb314f.png)

**Comment by nzkller** [comment]
Thank you!! Love your work, please keep it up!
