### ISSUE TITLE
[FEAT] Publish Docker images in GitHub Registry

### ISSUE THREAD

**Issue by ngosang** [CorentinTh/it-tools#304]
**Is your feature request related to a problem? Please describe.**
Thank you for publishing the Docker image in DockerHub. That is good enough for me, but DockerHub is changing the rules lately.
* https://docs.docker.com/docker-hub/download-rate-limit/
* https://www.infoworld.com/article/3690890/docker-sunsets-free-team-subscriptions-roiling-open-source-projects.html

They reverted the latest decision but it's desirable to have a mirror just in case.

**Describe the solution you'd like**
Publish the Docker image in DockerHub and in GitHub Container Registry, both.
* GitHub action example to publish both => https://github.com/ngosang/restic-exporter/blob/main/.github/workflows/release-docker.yml
* GitHub Container Registry example image => https://github.com/ngosang/restic-exporter/pkgs/container/restic-exporter

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by CorentinTh** [comment]
Docker image are now nightly pushed to docker hub and github packages under the **nightly** tag (`docker pull ghcr.io/corentinth/it-tools:nightly`)
