### ISSUE TITLE
[FEAT] New tool JSON abc / sort

### ISSUE THREAD

**Issue by ngosang** [CorentinTh/it-tools#306]
**Is your feature request related to a problem? Please describe.**
New tool JSON abc / sort. It will receive a JSON as input and it will return a beautiful JSON with the keys ordered alphabetically. 
It's useful to compare JSON files and when you are working with big files.
You could include this feature as an option in "JSON prettify and format" tool or as a new tool.
![image](https://user-images.githubusercontent.com/10577978/228527417-bb09f1b8-5a77-4e03-94d0-efd39e371a9c.png)

**Describe the solution you'd like**
Example tools 
* https://jsonsort.net/
* https://novicelab.org/jsonabc/

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by CorentinTh** [comment]
Done ✅ 
Added a few config in the json prettifier 

https://it-tools.tech/json-prettify

![screely-1680125626413](https://user-images.githubusercontent.com/25065347/228673010-08dbde35-ada7-4cf5-b0de-ba8ab90b92b4.png)

**Comment by ngosang** [comment]
Thank you!

**Comment by ngosang** [comment]
@CorentinTh
1) I think this toogle should be false by default. Sorting is only useful for comparing.
2) If I set indent = 0, I get the same result as in the JSON minify tool. Maybe you should merge both tools and add a toogle to minimize?
