### ISSUE TITLE
[FEAT] New tool JSON ABC and Diff

### ISSUE THREAD

**Issue by ngosang** [CorentinTh/it-tools#307]
**Is your feature request related to a problem? Please describe.**
New tool JSON ABC and Diff. Comparing JSON files could be time consuming since the JSON keys can be in different order. In this case usual diff tools don't work well.
The tool must receive 2 JSON files. You should apply JSON sort (#306) and beautify to both JSONs. Compare both files and show the differences. This could be useful for a future "text diff" tool (#294).

![image](https://user-images.githubusercontent.com/10577978/228529191-4c360fed-fa10-4b32-9c2d-f80e36a5daa8.png)

**Describe the solution you'd like**
* Example tool => https://novicelab.org/jsonsortdiff/#diff

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by ngosang** [comment]
Thank you. It's almost perfect. In the screenshot you can see the green code is not formatted.

![image](https://user-images.githubusercontent.com/10577978/233976667-b408b807-679c-466f-8a3d-96e8288e51f3.png)


```
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}

```

**Comment by ngosang** [comment]
@CorentinTh the issue in the last comment is still present. Could you check it?

**Comment by CorentinTh** [comment]
Please reopen an issue so I can keep track 🙏
