### ISSUE TITLE
[FEAT] New tool: regular expression evaluator (regex)

### ISSUE THREAD

**Issue by ngosang** [CorentinTh/it-tools#308]
**Is your feature request related to a problem? Please describe.**
I would like to have a tool similar to => https://regex101.com/
It has too many features but you can start with a simple regular expression evaluator. The user will provide a regular expression and a sample text. The tool will tell if the regular expression is valid, apply to the text, show it the expression matches the text. Show the "match groups" if the expression has groups.

**Describe the solution you'd like**
I would like to have a tool similar to => https://regex101.com/

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by sharevb** [comment]
Hi @ngosang  and @CorentinTh, implemented in #1030
