### ISSUE TITLE
XLM/JSON/YAML converter

### ISSUE THREAD

**Issue by ephraim-beltran** [CorentinTh/it-tools#314]
**Is your feature request related to a problem? Please describe.**
I sometimes get DMARC reports in XML format but it doesn't happen enough to warrant a separate service to parse.
I often just do a quick google search for XML to JSON converter to make it more readable.

Something similar to https://codebeautify.org/xmltojson would be a nice feature.

**Comment by CorentinTh** [comment]
JSON <-> YAML converters are live !

https://it-tools.tech/json-to-yaml-converter

![screely-1681158961670](https://user-images.githubusercontent.com/25065347/231281065-d0be21fb-593f-4eef-963b-db80bb671e61.png)

**Comment by sharevb** [comment]
Hi @CorentinTh and @ephraim-beltran, XML <> JSON implemented in #1231
