### ISSUE TITLE
[BUG] OTP code generator wrong values after stale tab

### ISSUE THREAD

**Issue by AllDayAlone** [CorentinTh/it-tools#315]
**Describe the bug**
OTP code generator gives wrong codes when you come back from other tab after a while

**To Reproduce**
1. Go to OTP code generator 
2. Remember the codes: A, B, C
3. Go to another tab and wait one cycle (20 seconds)
4. Come back to it-tools and check the codes. They are exactly the same A, B, C
5. Wait for another cycle, they are normal as expected: C, D, E

**Expected behavior**
On step 4 of the reproduce, they should be B, C, D

**Video**
Pay attention to all three codes. Pause on the video is ~20 seconds
https://www.loom.com/share/509318fa37ed4ea9a88089d69c602df3

**Configuration (please complete the following information):**
 - MacOS,  chrome

**Additional context**

**Comment by CorentinTh** [comment]
Hi @AllDayAlone 
Thank you for reporting this issue

I'll add a refresh on new window focus since interval may be paused on tab dismiss

**Comment by AllDayAlone** [comment]
@CorentinTh with that fix, another critical bug was introduced, now it doesn't allow to paste custom secret :(

**Comment by CorentinTh** [comment]
Thanks @AllDayAlone, I should have tested more, it's fixed
