### ISSUE TITLE
[FEAT] Manual Sorting and storage of favorites order

### ISSUE THREAD

**Issue by pyunramura** [CorentinTh/it-tools#316]
**Is your feature request related to a problem? Please describe.**

Not a problem per-se but a nice convenience feature. Having my most used tools pinned at the top of the page, it would be nice to be able to order them when I pin a new favorite. 

For example the new ipv4 subnet calculator I just pinned is at the bottom of the list of my favorites and to have it at the top of my pinned tools I'll need to write down the order I'd like them in, unpin them all, then re-pin in my preferred order and repeat this process anytime I'd like to modify the pinned tools.

**Describe the solution you'd like**

I'd like to be able to manually sort the order of my pinned (favorite) tools and have that stored persistently by the browser. A nice drag-and-drop interaction would be a plus from a usability standpoint.

**Describe alternatives you've considered**

Currently I'm having to unpin all of my favorites and re-pin them in my preferred order and repeat this process anytime my preferences change. Not the worst inconvenience by any stretch, but certainly something that could make the UX a bit better.

**Additional context**

No additional context, but I'd sincerely like to thank the author and contributors to this project, you are doing great work here. I found mention of it on noted.lol and immediately knew it would be a boon and I am overjoyed with the project so far. So thank you again.

**Comment by webysther** [comment]
I change of machine very often, have this option really help

**Comment by gitmotion** [comment]
@CorentinTh @pyunramura @binuengoor @webysther 
added drag-and-drop favorites ordering here: https://github.com/CorentinTh/it-tools/pull/1360

**Comment by gitmotion** [comment]
@pyunramura @binuengoor @webysther 

since PRs are a bit backed up you can use this image in your docker-compose file if you want this functionality along with my other additions as well until the main branch has been updated:

**docker image:**
```
ghcr.io/gitmotion/it-tools:latest
```
- you may need to clear cache and hard reload to get new features loading

#### OR locally
**github repo:**
```
git clone -b gitmotion/main https://github.com/gitmotion/it-tools.git
pnpm i && pnpm dev
``` 
- (installing packages for the first time may take some time)

**Comment by gitmotion** [comment]
@pyunramura @binuengoor @webysther this has been merged! you can pull the latest docker image or try it out on it-tools.tech. You may need to hard reload (ctrl+r / cmd+r)
