### ISSUE TITLE
[BUG] Docker build failed 

### ISSUE THREAD

**Issue by MadalinNitu** [CorentinTh/it-tools#320]
I got the following error when I try to build the Docker image locally:

`docker build -t it-tools -f Dockerfile .`

` > [build-stage 6/6] RUN pnpm build:
#0 1.062 
#0 1.062 > it-tools@2.19.0 build /app
#0 1.062 > vue-tsc --noEmit && vite build
#0 1.062 
#0 3.613 vite v2.9.15 building for production...
#0 3.685 transforming...
#0 40.15 
#0 40.15 <--- Last few GCs --->
#0 40.15 
#0 40.15 [16:0x7f34f1a4a2e0]    37223 ms: Scavenge (reduce) 982.3 (1008.2) -> 981.7 (1008.4) MB, 3.1 / 0.0 ms  (average mu = 0.158, current mu = 0.032) allocation failure; 
#0 40.15 [16:0x7f34f1a4a2e0]    37256 ms: Scavenge (reduce) 982.4 (1008.4) -> 981.9 (1008.7) MB, 20.1 / 0.0 ms  (average mu = 0.158, current mu = 0.032) task; 
#0 40.15 [16:0x7f34f1a4a2e0]    37280 ms: Scavenge (reduce) 982.7 (1008.7) -> 982.1 (1008.9) MB, 9.3 / 0.0 ms  (average mu = 0.158, current mu = 0.032) allocation failure; 
#0 40.16 
#0 40.16 
#0 40.16 <--- JS stacktrace --->
#0 40.16 
#0 40.16 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
#0 40.59  ELIFECYCLE  Command failed.
------
Dockerfile:7
--------------------
   5 |     RUN npm install -g pnpm
   6 |     RUN pnpm i --frozen-lockfile
   7 | >>> RUN pnpm build
   8 |     
   9 |     # production stage
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm build" did not complete successfully: exit code: 1
`

**Comment by CorentinTh** [comment]
Hi @MadalinNitu 
I will need more details, like your OS and the platerform on which you are trying to build the docker image

It looks like an OOM issue, on many RAM do you have ?

**Comment by MadalinNitu** [comment]
I have a vm with 4ram 4 cpu and I got the error but now I try again on my host with 32 ram and its work fine.

Thank you
