### ISSUE TITLE
Feature Request: User Agent Explainer

### ISSUE THREAD

**Issue by benniblot** [CorentinTh/it-tools#322]
Hey, think it would be cool if there would be a tool that analyses a user-agent string or the user-agent of the website visitor.

Something like this:
User Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"

Analysis:
**Browser:** Chrome 111.0.0.0
**Browser Kernel:** Blink 111.0.0.0
**Device:** unknown vendor unknown device type
**System:** Windows 10
**CPU Arch:** amd64

**Comment by CorentinTh** [comment]
It's done ✅ 
Thanks to @cgoIT 🙏🏻 

https://it-tools.tech/user-agent-parser

![screely-1680769944686](https://user-images.githubusercontent.com/25065347/230322213-c27a7304-eff9-449f-b458-c8566c41bd87.png)

**Comment by benniblot** [comment]
Thanks a lot :)
