### ISSUE TITLE
QR generator: Multiple text lines

### ISSUE THREAD

**Issue by nluttikhuizen** [CorentinTh/it-tools#324]
**Multiple lines support in the text form of the QR-Code generator**
The tool doesn't support multiple lines, so for example we can't use the tool for generating wirequard qr-codes. And I would love to use it for Wireguard.

**Comment by CorentinTh** [comment]
Done ✅ 
You can now specify multiple line in the qr-code generator 

https://it-tools.tech/qrcode-generator

![screely-1680735365473](https://user-images.githubusercontent.com/25065347/230229929-3d2c4569-595b-4cb2-85fe-89dc5142c5b0.png)

**Comment by nluttikhuizen** [comment]
Great work!
