### ISSUE TITLE
Is there a way to disable plausible analytics when self-hosting?

### ISSUE THREAD

**Issue by dhersam** [CorentinTh/it-tools#325]
I noticed the app attempts to POST to `/api/event` with an analytics payload and fails with a 405 on my self-hosted instance. Is there a way to disable analytics entirely?

Thanks for making this great suite of tools, they're really useful.

**Comment by CorentinTh** [comment]
Hi @dhersam 
Thank you for this feedback !
I'll disable plausible analytics by default

**Comment by CorentinTh** [comment]
Done, in the next docker release, plausible is disabled by default
