### ISSUE TITLE
IPv4 Converter

### ISSUE THREAD

**Issue by darkxfuneral** [CorentinTh/it-tools#341]
Hi,
Is it possible to add an IPv4 converter to it-tools? 
An IPv4 converter which Convert IP addresses to decimal format, integer format, IPv6 (short) and IPv6 (long).
just like this:
![ipv4 converter](https://user-images.githubusercontent.com/13685469/230679893-f6590303-d010-4587-adf7-40c654d0a463.jpg)
Thank you.

**Comment by CorentinTh** [comment]
Done ✅ 

https://it-tools.tech/ipv4-address-converter

![screely-1680981269797](https://user-images.githubusercontent.com/25065347/230738926-56aa38b0-7692-4892-9bca-e610990dc86a.png)

**Comment by darkxfuneral** [comment]
Thank you very much!!
