### ISSUE TITLE
[BUG] Copy buttons not working

### ISSUE THREAD

**Issue by TheSelox** [CorentinTh/it-tools#342]
Hi there. I love the app, but I noticed the copy button is not working for me in any of the tools.
I tried it on Firefox, Chrome and Firefox mobile (latest beta).

Keep up the good work :)

**Which tool is impacted?**
All tools which use a copy button

**To Reproduce**

1. Go to any page with a copy button (e.g. "Token generator")
2. Click on 'Copy'
3. Message with 'X copied to clipboard' shows up
4. Values are not in clipboard

**Configuration (please complete the following information):**

- Device: PC, Pixel 6
- OS: Windows 10, Android 13
- Browser Firefox, Chrome, Firefox mobile
- Version: all latest patch level

**Comment by CorentinTh** [comment]
Hi @TheSelox 
That's strange, it work for me, using chrome on ubuntu 22 and on my Pixel 6 Pro too on https://it-tools.tech/token-generator

**Comment by cgoIT** [comment]
Works for me on iPhone 13 with iOS 16.4.1

**Comment by TheSelox** [comment]
Ok I think I've found the issue:

[Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard):
`Secure context: This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.`

Since I'm not a web developer I didn't know that copying with JS is prevented on HTTP sites.

I'm only using the self-hosted app within my LAN and didn't assign an SSL cert.

So my bad and TIL :)
