### ISSUE TITLE
IT-Tools doesn't open on Pale Moon browser [BUG] 

### ISSUE THREAD

**Issue by noellarkin** [CorentinTh/it-tools#353]
**Which tool is impacted?**
The entire application.

**To Reproduce**

1. Install pale moon browser and dockerized it-tools
2. press CTRL+SHIFT+I to open browser console
3. Open it-tools instance
4. See error in console:
`SyntaxError: expected expression, got keyword 'import'[Learn More]  index.2ef32d6d.js:1859:47211`

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**

- Device: Desktop
- OS: Windows 10
- Browser: Pale Moon
- Version: 32

**Additional context**
Dynamic importing of JS modules isn't supported in all browsers (Pale Moon, Seamonkey etc).

**Comment by CorentinTh** [comment]
Hi @noellarkin thank you for reporting this bug 

Unfortunately, I currently have no plans to support such uncommon browsers. The trade-off between the effort required and the number of people needing this support is currently too high, hope you understand 🙏🏻
