### ISSUE TITLE
[TOOL IMPROVEMENT] Remove Autofilled NaN in UUID Generator

### ISSUE THREAD

**Issue by joe-eklund** [CorentinTh/it-tools#357]
**Describe the solution you'd like**
When putting in a custom number for the UUID generator, when I delete the number to put in a new number, `NaN` is autofilled. This means I also have to delete that before I can input my number. I would suggest not autofilling `NaN`, as it doesn't really serve any purpose.

**Additional context**
Add any other context about the feature request here.

**Comment by CorentinTh** [comment]
Thanks for the report !
It's fixed 

https://it-tools.tech/uuid-generator

![screely-1681421885519](https://user-images.githubusercontent.com/25065347/231888687-9148eff4-df26-41b0-8fc5-719c2f007511.png)
