### ISSUE TITLE
[NEW TOOL] pics generator

### ISSUE THREAD

**Issue by fatahnuram** [CorentinTh/it-tools#367]
**Which tool is impacted?**
Example: picture generator

**Describe the solution you'd like**
generate picture via REST API

**Is their example of this tool in the wild?**
[lorem picsum](https://picsum.photos/)

**Additional context**
you can see lorem picsum yourself.

**Comment by CorentinTh** [comment]
Hi @fatahnuram 
Thank you for this great idea, but since IT-Tools is client side only, it cannot act as an API
So the best we can do is an image placeholder downloader, and their is already one : https://it-tools.tech/svg-placeholder-generator
