### ISSUE TITLE
[BUG] Token generator Copy Button not work

### ISSUE THREAD

**Issue by Mike710Shine** [CorentinTh/it-tools#384]
**Which tool is impacted?**
The token generator

**To Reproduce**
1. Click on Refresh 
2. Click on Copy and 
3. Go to a editor of your choice and hit CTRL+V or try right click an past 

nothing will happen. I think the copy button don't work.

**Expected behavior**
When i click on copy it should copy the token to the clipboard

**Configuration (please complete the following information):**

- Device: Windows PC
- OS: Windows 11
- Browser Opera, Chrome
- Version Opera: LVL 4 (core: 97.0.4719.89), Chrome: 112.0.5615.138

**Comment by CorentinTh** [comment]
Are you on HTTPS ?
Copy work only on secure endpoint

**Comment by CorentinTh** [comment]
Looks related to #342

**Comment by Mike710Shine** [comment]
Ahh ok thats was the Problem i think i have only a http reverse proxy created i think i should upgrade it to https. Thanks for the response and thanks for the hin with #342
