### ISSUE TITLE
[BUG] Every phone number without country prefix seems to be from France

### ISSUE THREAD

**Issue by cgoIT** [CorentinTh/it-tools#389]
**Which tool is impacted?**
Phone parser and formatter

**To Reproduce**

1. Go to 'Phone parser and formatter'
2. Select Germany as Default Country code
3. Insert any phone number (e.g. 06991320)
4. Result "Country => France"

**Expected behavior**
If a number is added without country code (doesn't start with 00 or +) the default country code should be taken

- Device: MacBook Pro
- OS: MacOS 13.3.1
- Browser Chrome, Firefox, Safari

**Additional context**
If desired I can have a look if I find the error

**Comment by CorentinTh** [comment]
Hi!
Thanks for the report, indeed a small mistake, fixed in #391
