### ISSUE TITLE
ARM64 Version

### ISSUE THREAD

**Issue by Dean2994** [CorentinTh/it-tools#396]
Hi, 

I really love your creation of this tool. 

Could you please make a ARM64 version of this so that I can run this on my raspberry pi in docker?

Thank you

**Comment by CorentinTh** [comment]
Hello @Dean2994 
Their is already a ARM64 version of the docker image, you can see on the docker hub : https://hub.docker.com/repository/docker/corentinth/it-tools/tags?page=1&ordering=last_updated
