### ISSUE TITLE
[BUG] IPv4 input field is no longer editable

### ISSUE THREAD

**Issue by cgoIT** [CorentinTh/it-tools#402]
**Which tool is impacted?**
IPv4 address converter

**To Reproduce**
Open IPv4 address converter
Try to edit IPv4

Will provide a fix soon

**Comment by CorentinTh** [comment]
Thanks for the report 🙏🏻  fixing now

How did you find out ?

**Comment by cgoIT** [comment]
Yes, indeed by using the tool. I want to fix #399 (which I've done now) and want to see what the binary representation of an ip is. ;)
