### ISSUE TITLE
[BUG] Base64 string encoder/decoder cannot convert Chinese/Japanese/Korean etc. strings

### ISSUE THREAD

**Issue by jasoncheng7115** [CorentinTh/it-tools#409]
**Which tool is impacted?**
Base64 string encoder/decoder

**To Reproduce**
Enter Base64 string encoder/decoder, enter text (Chinese/Japanese/Korean, etc.) in the string to encode field.

**Expected behavior**
Base64 of string field will disappear.

**Screenshots**
![image](https://github.com/CorentinTh/it-tools/assets/30381035/d129f31b-7d0f-409e-a0ef-c8fab7f04841)

**Configuration (please complete the following information):**

- Device: Macbook Pro 2020
- OS: macOS 12.5.1
- Browser: Chrome
- Version 113

**Comment by lemon8866** [comment]
Windows. btoa does not support ANSI type text encoding
I added window. btoa (unescape (encodeURIComponent (str))); And decodeURIComponent (escape (window. atob (str));   #732

**Comment by sharevb** [comment]
Hi @jasoncheng7115 and @CorentinTh, fixed in #905

**Comment by CorentinTh** [comment]
Solved in #905
