### ISSUE TITLE
Pretty XML (feature)

### ISSUE THREAD

**Issue by jicho** [CorentinTh/it-tools#419]
Hi,

I like the pretty JSON option (and other options ;), any plans to add a "Pretty XML" option?

I'm thinking about the simple version that changes this:
`<example><something>hi</something></example>`

Into:
```
<example>
    <something>hi</something>
</example>
```

Keep up the great work with this project!

**Comment by jmmanzano** [comment]
Hi. That tool is already created.
https://github.com/CorentinTh/it-tools/pull/457
