### ISSUE TITLE
[TOOL IMPROVEMENT] Fuzzy finding in "Phone parser and formatter" for sorting by country calling code

### ISSUE THREAD

**Issue by Leon358522** [CorentinTh/it-tools#420]
**Describe the solution you'd like**
 A field in the "Phone parser and formatter" that allows you to sort by a specific country calling code 
Maybe with fuzzy finding 

**Additional context**
I could just google the country related to a country calling code, but this would make searching it up possible without internet access and scrolling down the whole country list until you found the right country

![image](https://github.com/CorentinTh/it-tools/assets/29558026/fa3f57b6-2ccd-4506-bcbd-cfc1aabfea15)

**Comment by CorentinTh** [comment]
Hi @Leon358522 
Thank you for submiting this issue, it's [now a feature](https://it-tools.tech/phone-parser-and-formatter)!
