### ISSUE TITLE
[FEAT] DNS / MX

### ISSUE THREAD

**Issue by marvingerstner** [CorentinTh/it-tools#431]
Hello, I need a tool to read DNS entries like MX TOOLBOX in IT-Tools. Can you add the function?

**Comment by CorentinTh** [comment]
Hi @marvingerstner !
Please refer to https://github.com/CorentinTh/it-tools/issues/412#issuecomment-1556685473

**Comment by sharevb** [comment]
Hi @marvingerstner  and @CorentinTh, DNS queries over HTTPS implemented in https://github.com/CorentinTh/it-tools/pull/1371
