### ISSUE TITLE
[OTHER] Login screen - request for information

### ISSUE THREAD

**Issue by jasek5** [CorentinTh/it-tools#432]
**Describe the solution you'd like**
I was unable to find, if it is possible to add "simple user management". i would like to selfhost the it-tools, but I want to limit the user access to it. Simply by login.

**Additional context**
Also SAML, LDAP or OPENID would be nice.

P.S.: I know that I can use something like Authelia, Authentik etc.. to "secure" the webpage, but I was curious.

Thank you very much!

**Comment by CorentinTh** [comment]
Hi @jasek5,

Thank you for raising this concern.

At this moment, user authentication is not available.

Given that the website is solely static and client-side, there is no data maintained on the server, and as such, I struggle to see the necessity for protective measures.

If you're interested in safeguarding your publicly accessible, self-hosted instance, I have some reservations.
- serving a log-in page would generate a similar load as serving a tool
- the majority of users will likely prefer using the official instance hosted on it-tools.tech
- again, given the static nature of the site, there are no inherent security issues

But maybe I'm missing something. If there's a piece of the puzzle I'm not seeing, feel free to fill me in!

**Comment by cgoIT** [comment]
Mmh,

as @CorentinTh pointed out the only thing your webserver does in case of this tool is to provide the user the ability to download some files (the tool). After that step no further request is done from the tool to your server. If this is the case then the question must be allowed: "How to you ensure that only valid users are allowed to open the login page to the tool?". For me it's some sort of a chicke-egg-problem.
If you really want to ensure that here are some options that come into my mind:

- simple basic authentication
- place it-tools behind a reverse proxy and do the authentication there
- use mutual tls (but this requires you to provide a client certificate to every valid user including the management of those client certificates)

Just my two cents....

**Comment by CorentinTh** [comment]
Closing as not implementing for the moment, will reopen if needed
