### ISSUE TITLE
[OTHER] Healthcheck endpoint

### ISSUE THREAD

**Issue by hibare** [CorentinTh/it-tools#435]
**Describe the solution you'd like**
Add a health check endpoint, something like `/health`. This will be useful to monitor application uptime.

**Additional context**
Add any other context about the feature request here.

**Comment by CorentinTh** [comment]
Hey @hibare,

Thanks for the suggestion! 😊 Just to clarify, our app is solely client-side, which means it doesn't actually have a server where we could add endpoints like /health. Essentially, the app runs directly in the browser, so there isn't an "uptime" in the traditional sense to monitor.

However, if you're thinking of monitoring whether the app is being served properly, that's more on the hosting side of things. Maybe consider looking into monitoring tools that can check if the webpage is up.

If you had something else in mind, or if you've got more ideas, I'm all ears!
