### ISSUE TITLE
[NEW TOOL] JSON to CSV

### ISSUE THREAD

**Issue by wen-long** [CorentinTh/it-tools#441]
**What tool do you want?**
Example: 

```
[
    {'Age': 18.0, 'Salary': 20000.0, 'Gender': 'Male', 'Country': 'Germany', 'Purchased': 'N'},
    {'Age': 19.0, 'Salary': 22000.0, 'Gender': 'Female', 'Country': 'France', 'Purchased': 'N'},
    {'Age': 20.0, 'Salary': 24000.0, 'Gender': 'Female', 'Country': 'England', 'Purchased': 'N'}
]
```

to
```
Age,Salary,Gender,Country,Purchased
18,20000,Male,Germany,N
19,22000,Female,France,N
20,24000,Female,England,N
```

**Describe the solution you'd like**
Input json, output csv in plain text, and if make it better, make a table filled with data

**Is their example of this tool in the wild?**
this is some links to already existing tool
https://www.convertcsv.com/json-to-csv.htm
https://data.page/json/csv
https://konklone.io/json/

**Additional context**
No.

**Comment by CorentinTh** [comment]
Hi, 
Thank you for the request !
It's done -> https://it-tools.tech/json-to-csv

![screely-1687104799912](https://github.com/CorentinTh/it-tools/assets/25065347/deb82488-7572-425d-bcb3-7576d652306d)
