### ISSUE TITLE
[BUG] Spelling error in MIME Type tool

### ISSUE THREAD

**Issue by lukasgabriel** [CorentinTh/it-tools#467]
Not sure if intentional, but there are 2 spelling mistakes in the 'MIME types' tool:

https://github.com/CorentinTh/it-tools/blob/bcb98b359c1a7fa39ee2bd72776dbb0434de150e/src/tools/mime-types/mime-types.vue#L27

https://github.com/CorentinTh/it-tools/blob/bcb98b359c1a7fa39ee2bd72776dbb0434de150e/src/tools/mime-types/mime-types.vue#L63

Again, not sure if intentional. 

The spelling should be "Know which..."

**Comment by CorentinTh** [comment]
Hi @lukasgabriel 
Thank you for spotting those awful typos! 
It's fixed 👌🏻
