### ISSUE TITLE
[NEW TOOL] Password strength checker.

### ISSUE THREAD

**Issue by lukasgabriel** [CorentinTh/it-tools#473]
**What tool do you want?**
A password strength meter/checker.

**Describe the solution you'd like**
A text box where you can enter a password.

It calculates the expected time to crack this password assuming it's hashed with a commonly used hash function like SHA256 (or lets the user pick one from several) and the maximum current feasible hash rate for that function (could also allow user input for that.)

It can also check against lists like [this](https://github.com/danielmiessler/SecLists/tree/master/Passwords) to determine if the password is vulnerable to a dictionary/wordlist attack.

Additionally, it should adapt its estimates based on the character set in the password (only lowercase, lower+uppercase, alphanumerical, abc+special characters.)

**Is there an example of this tool in the wild?**
https://www.security.org/how-secure-is-my-password/ (Formerly: https://howsecureismypassword.net/)
https://www.passwordmonster.com/ (is, in my opinion, the gold standard for this.)

**Additional context**
This would be useful for checking (or demonstrating to others) the strength/weakness of a password without having to enter it anywhere out of one's control (like on the sites mentioned above.)

Sometimes I would like to convince a coworker or friend that, in the age of GPU/FPGA-accelerated hash cracking, an 8-character alphanumeric password isn't all that strong anymore.

---

I'd LOVE to help with this tool! Unfortunately I don't "speak" JS/TS 😢 
This is kind of a "long shot" request so if this is totally out of scope for this project I completely understand 😄 

It's just something that I always wanted to have an offline/self-hosted version of, since entering other people's passwords (or even corporate ones) on a random website to demonstrate their weakness to friends/coworkers mostly doesn't go so well 😆

**Comment by CorentinTh** [comment]
Hi @lukasgabriel 
It's done : https://it-tools.tech/password-strength-analyser

![image](https://github.com/CorentinTh/it-tools/assets/25065347/28a60060-a120-4cb5-95fd-9af5d05d1235)

**Comment by lukasgabriel** [comment]
@CorentinTh Wow! Impressive that you got that done in so little time. It's pretty much exactly what I wanted! 😄

Now that the groundwork is laid, maybe I will try my hand at implementing dictionary checking.

Thanks again!
