### ISSUE TITLE
[BUG] Light and Dark mode are unreadable in Safari

### ISSUE THREAD

**Issue by gofastlily** [CorentinTh/it-tools#541]
**Which tool is impacted?**
All tools in the IT Tools app

**To Reproduce**

1. Open page in Safari
2. Change to Dark/Light mode and invert the issue

**Expected behavior**
I would expect IT Tools to appear as it does in Firefox (that is to say, is perfectly readable).

**Screenshots**
Light Mode:
<img width="988" alt="Screenshot 2023-07-19 at 12 39 24 PM" src="https://github.com/CorentinTh/it-tools/assets/120291200/7275a7eb-98bf-4a04-8f9b-a6a4e9fa81a7">

Dark Mode:
<img width="914" alt="Screenshot 2023-07-19 at 12 39 29 PM" src="https://github.com/CorentinTh/it-tools/assets/120291200/fe3f5f40-e43c-4c68-b3dc-54c6b0ffd37d">

**Configuration (please complete the following information):**
- Device: MacBook Air (M2, 2022)
- OS: macOS 13.4.1
- Browser: Safari
- Version: 16.5.2

**Additional context**
Both Light and Dark modes are unusable

**Comment by CorentinTh** [comment]
HI @gofastlily 
Thank you for reporting this issue
That's an old bug of themes that are out of sync with the ui component library, you can easily fix it by clearing your localstorage, or updating to the latest it-tools version

**Comment by gofastlily** [comment]
That fixed it, thank you!
