### ISSUE TITLE
Emoji Page?

### ISSUE THREAD

**Issue by SMAW** [CorentinTh/it-tools#547]
**What tool do you want?**
An page with all the emoji's so you can copy them and paste them whereever

**Describe the solution you'd like**
An page like [this](https://getemoji.com/) where all the emoji's are for copy and pasting into MD or something

**Is their example of this tool in the wild?**
https://getemoji.com/

**Additional context**
Should be realitve easy I think but will help me alot... (Just make an page and copy all the emoji's there, so I can copy them from there.

**Comment by CorentinTh** [comment]
Hello @SMAW 
Thanks for the idea, it's done in #551 
Have a look : https://it-tools.tech/emoji-picker
![screely-1691526541495](https://github.com/CorentinTh/it-tools/assets/25065347/de0ad54c-9658-48db-b88d-dbb49bbdb03f)
