### ISSUE TITLE
[NEW TOOL] RegEx Build and Test

### ISSUE THREAD

**Issue by wuergezwerg** [CorentinTh/it-tools#554]
It would be nice to have a "RegEx Build and Test" tool similar to https://regexr.com/. It really helps to create regex when you only need it once every 2 months. The option to look at the different expressions in the cheatsheet helps to remember also :D

**Comment by Nezteb** [comment]
Duplicate of https://github.com/CorentinTh/it-tools/issues/308 (which technically came first), though this issue's `[NEW TOOL]` is the correct prefix. 😄

**Comment by sharevb** [comment]
Hi @wuergezwerg  and @CorentinTh, implemented in #1030
