### ISSUE TITLE
[OTHER] Missing tools in docker compose 

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CorentinTh/it-tools#574]
When self-hosting IT-Tools I noticed that some tools that are in src/tools (like password strenght analyzer) or on https://it-tools.tech are missing in the self-hosted version. How can I add them?

**Comment by CorentinTh** [comment]
Hi @Unrepentant-Atheist 
Thank you for taking the time to submit this issue 🙏🏻 
I've just made a new docker release with all the missing tools and the latest version, see here : https://github.com/CorentinTh/it-tools/releases/tag/v2023.8.16-9bd4ad4
