### ISSUE TITLE
[BUG] Slugify does not work for single character s and t

### ISSUE THREAD

**Issue by Joniator** [CorentinTh/it-tools#593]
**Which tool is impacted?**
[Slugify](https://it-tools.tech/slugify-string)

**To Reproduce**

1. Enter `Test t`
2. Expect `test-t`, get `testt`
3. Add an e, so you input `Test te`
4. Get the expected `test-te`

Putting the broken characters with single space between each seperates them as pairs:
Input: `s s s s s s s`
Output: `ss-ss-ss-s`

Most characters work, only s and t behave like this.

**Configuration (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Edge
- Version: 116.0.1938.62 (Official build) (64-bit)

**Comment by im-sellar** [comment]
Hey everyone !
Updating @sindresorhus/slugify from version 2.2.0 to 2.2.1 fixes the issue.
Here is the PR : https://github.com/CorentinTh/it-tools/pull/673

**Comment by sharevb** [comment]
Hi @CorentinTh and @Joniator, sounds fixed right now, could be closed
