### ISSUE TITLE
[TOOL IMPROVEMENT] Base64 image viewer

### ISSUE THREAD

**Issue by agc93** [CorentinTh/it-tools#594]
**Describe the solution you'd like**
The existing Base64 file converter is useful for converting images stored in base64/Data URI format to a real image, but it would be even better if images could be viewed inline without having to download and open.

**Additional context**
An example of this functionality is [this tool](http://jaredwinick.github.io/base64-image-viewer/) ([source here](https://github.com/jaredwinick/base64-image-viewer/tree/gh-pages))

**Comment by sharevb** [comment]
Hi @vlasovt, @xiaohongred, implemented in #905, thanks to @SAF2k for preview image part
