### ISSUE TITLE
[Feature] Create multiple UUIDs

### ISSUE THREAD

**Issue by alexanderjanke** [CorentinTh/it-tools#6]
**Is your feature request related to a problem? Please describe.**
Manually creating a set of multiple UUIDs is tedious when only being able to create a single one at a time.

**Describe the solution you'd like**
A textbox to enter a amount of UUIDs that should be created

**Describe alternatives you've considered**
None

**Additional context**
Example design
![image](https://user-images.githubusercontent.com/33967771/84056246-41b8e600-a9b6-11ea-9879-51912193dd69.png)

Actual usage when copying multiple values:
![mockdata_example](https://user-images.githubusercontent.com/33967771/84056987-48942880-a9b7-11ea-85f4-0d04666c6398.gif)

**Comment by CorentinTh** [comment]
Thanks for your feedback!

That's a good point, I'll implement it, it seems really usefull.

**Comment by CorentinTh** [comment]
Done!

![image](https://user-images.githubusercontent.com/25065347/84060451-83e52600-a9bc-11ea-831e-ac1999f14a6c.png)

Have fun [it-tools.tech/#/uuid-generator](https://it-tools.tech/#/uuid-generator) (remember to invalidate cache to have latest version: `Shift` + `F5`)
