### ISSUE TITLE
[OTHER] Add a search bar at the top of the sidebar

### ISSUE THREAD

**Issue by sbordeyne** [CorentinTh/it-tools#600]
**Describe the solution you'd like**

Add a search bar at the top of the sidebar. This tool is awesome, but there are a lot of tools, therefore being able to search for them (and Cmd + K / Ctrl + K to focus on the search) would be a nice addition.

**Additional context**

**Comment by CorentinTh** [comment]
Hi @sbordeyne 
Their is already a huge search bar with command palet features, focussable with Ctrl/Cmd+K 🤔 
Am I missing something ?

![image](https://github.com/CorentinTh/it-tools/assets/25065347/1e887e23-4166-4f5f-af22-159f166326b6)

**Comment by sbordeyne** [comment]
My bad, I was scrolling down and I didn't see it 😄
