### ISSUE TITLE
[NEW TOOL] ULID generator

### ISSUE THREAD

**Issue by cheatsnake** [CorentinTh/it-tools#619]
**What tool do you want?**
ULID (Universally Unique Lexicographically Sortable Identifier) generator

**Describe the solution you'd like**
The same generator page as for UUID.
Need an field for quantity of IDs and other one for result output.
ULID is based on timestamps therefore if can be usefull to add an field to input desired date.

**Is their example of this tool in the wild?**
Online generator: https://ulidgenerator.com
Offical JavaScript library: https://github.com/ulid/javascript

**Additional context**
Official spec: https://github.com/ulid/spec

**Comment by CorentinTh** [comment]
Hi @cheatsnake !

Thank you for the idea and the discovery, it's done and live : https://it-tools.tech/ulid-generator


![screely-1694473312770](https://github.com/CorentinTh/it-tools/assets/25065347/e3c2cc92-1c6f-4f7d-9d4d-01d4d50ca648)

**Comment by cheatsnake** [comment]
@CorentinTh You are awesome 🔥
