### ISSUE TITLE
ASCII Text to Binary Converter

### ISSUE THREAD

**Issue by cschwarck** [CorentinTh/it-tools#643]
**Feature request:**
I often find myself needing to convert text to its binary representation for various reasons (e.g., debugging, encoding analysis, educational purposes). It would be immensely useful to have this feature directly in your app, eliminating the need for third-party tools or manual conversions.

**Describe the solution you'd like**
I propose the addition of a "Text to Binary" converter feature in your app. The functionality could look something like this:

A user inputs a string of text.
The app provides the binary representation of each character in the input string.
The binary output is displayed either inline or in a separate output area.

**Describe alternatives you've considered**
There are some standalone online tools and libraries that offer this service, but having it integrated into your app would streamline the process and reduce the dependency on external resources.

**Additional context**
This feature would not only benefit users like me but could also be a valuable educational tool for those learning about binary encoding or computer science concepts. It would set your app apart as a multifunctional tool catering to a wider audience.

**Is their example of this tool in the wild?**
Example: https://www.convertbinary.com/text-to-binary/

**Additional context**
Text to Morse Code would be fun to have too!

Thank you for considering this feature request. I believe it would be a valuable addition and I'm excited to see the future developments of your app!

**Comment by martygo** [comment]
Hi! Here a function in vanilla JS to convert ASCII Text to Binary:

``function textToBinary(text) {
    return text.split('').map(function (char) {
        return char.charCodeAt(0).toString(2);
    }).join(' ');
}

let binary = textToBinary("Hello, World!");
console.log(binary);

**Comment by CorentinTh** [comment]
Hi @cschwarck 
Thank you for the suggestion, it's live : https://it-tools.tech/text-to-binary

![screely-1697410450288](https://github.com/CorentinTh/it-tools/assets/25065347/77f56c03-48b4-494e-abea-84c8c97dea46)
