### ISSUE TITLE
[NEW TOOL] Regular expression tool

### ISSUE THREAD

**Issue by AiJiangnan** [CorentinTh/it-tools#644]
**What tool do you want?**
Regular expression check and generator.

**Comment by lldm** [comment]
yeah, need it ! I use regex everyday.

**Comment by jaywehner** [comment]
Yeah that would be nice. but ChatGPT does a fantastic job of creating RegEx. Maybe they can add a CharGPT prompt using your own API account.

**Comment by sharevb** [comment]
Hi @AiJiangnan, @lldm, @jaywehner  and @CorentinTh, implemented in #1030
