### ISSUE TITLE
[NEW TOOL] Hello dear friend, don't be tired for your hard work.  Do you have a software that can automatically replace the 12 words trust wallet and show every available wallet

### ISSUE THREAD

**Issue by Yaserra** [CorentinTh/it-tools#647]
**What tool do you want?**
Example: a token generator

**Describe the solution you'd like**

**Is their example of this tool in the wild?**
Provide link to already existing tool or npm packages if any exists

**Additional context**
Add any other context about the feature request here.

**Comment by CorentinTh** [comment]
Hello @Yaserra 
Thank you for your interest in it-tools

Can you reopen an issue while following the issue template to help us understand what you want 🙏🏻
