### ISSUE TITLE
[NEW TOOL] RegExp Match Generator Tool

### ISSUE THREAD

**Issue by Nezteb** [CorentinTh/it-tools#649]
**What tool do you want?**

A regular expression match generator.

**Describe the solution you'd like**

Given a regex, the tool would generate random strings that match the regex.

**Is their example of this tool in the wild?**

- https://github.com/fent/randexp.js/
- http://fent.github.io/randexp.js/

**Additional context**

Similar to https://github.com/CorentinTh/it-tools/issues/308; will probably share similar regex code.

**Comment by sharevb** [comment]
Hi @Nezteb  and @CorentinTh, implemented in #1030
