### ISSUE TITLE
network debugging

### ISSUE THREAD

**Issue by drpdishant** [CorentinTh/it-tools#676]
**What tool do you want?**
Realtime Network Debugging Tools:
- DNS Checker
- Ports Checker
- Telnet(or equivalent to check port connectivity)
- Ping Tool

**Describe the solution you'd like**

Using relevant libraries we can implement these features.

**Is their example of this tool in the wild?**

I have build my own tooling for such use case, which I use on regular basis to debug service connectivity from my k8s cluster hosting a set of microservices.
https://codeberg.org/drpdishant/k8s-lab/src/branch/master/utils/netapi

**Additional context**

It will help dev and operations to debug network related issues without needing to access the cluster, or an air-gapped runtime environment.

**Comment by sharevb** [comment]
Hi @drpdishant , this is not really possible from a browser, JS cannot access everywhere and cannot do raw socket access, will require a local application or server side, so probably not the goal of this project

But maybe can just make links to other websites if you provide urls for such

**Comment by drpdishant** [comment]
> links

Yes, this will require a serverside component, which can act as an agent to initiate such checks.
Browser will set a POST or GET Request to the agent and in turn will get the response.

Something similar to what prometheus-blackbox-exporter does

**Comment by CorentinTh** [comment]
Hi @drpdishant 

Thank you for your suggestion. However, as stated by @sharevb, IT-Tools operates solely on the client side and is unable to perform such operations within the browser.
