### ISSUE TITLE
[BUG] Extra FF on color picker

### ISSUE THREAD

**Issue by jaywehner** [CorentinTh/it-tools#697]
**Which tool is impacted?**
Color generator

**To Reproduce**

Pick a color and it returns a 8 digit hex with a FF and the end. #24638AFF

**Expected behavior**
Just the # and six digit hex number: #24638A

**Screenshots**
attached screenshot

**Additional context**
This may be by design but seems suspect as not sure what the final FF is used for.

**Comment by SirYuxuan** [comment]
ff is alpha

**Comment by jaywehner** [comment]
Then there should be a second line that includes the alpha. Some software doesn't accept the alpha value and I have to remove it every time I use it. A small annoyance, but still could be fixed.

**Comment by CorentinTh** [comment]
Hi @jaywehner 

I slightly changed the behavior in #701 
The color picker will keep the extra `FF`, but the `hex` line will be stripped of extra alpha channel
Does this adjustment meet your requirements?

It's live : https://it-tools.tech/color-converter

![image](https://github.com/CorentinTh/it-tools/assets/25065347/5486d081-c5a8-4452-82bc-3fae10b3d165)

**Comment by jaywehner** [comment]
This is perfect. Excellent work on this project by the way! You can close the issue.
