### ISSUE TITLE
[TOOL IMPROVEMENT] Date-time converter - support Excel time

### ISSUE THREAD

**Issue by swishkin** [CorentinTh/it-tools#703]
**Describe the solution you'd like**
Add a line for Excel date/time, i.e. 

![image](https://github.com/CorentinTh/it-tools/assets/19404743/0e73039a-1633-4b2f-834b-473ba36f0571)

A day in Excel is measured as 1, and counts up from January 1st, 1900 with that date equal to 1.

The current date is 45229 in Excel's format.

Hours, minutes, and seconds are calculated by dividing 1 by the number of units in the day, so... 
1/24 = 1 hour, 1/24 x 60 = 1 minute, and 1/24 x 60 x 60 = 1 second.

**Additional context**

Being that you often need one or the other, or both, I would recommend allowing for copying Excel formatted **date and time**, Excel formatted **date**, and Excel formatted **time**, which would look like:

NOW() = 45229.91601065972
TODAY() = 45229
NOW() - TODAY() = 0.91601065972

Information on Excel's DATE and TIME functions [here](https://support.microsoft.com/en-us/office/date-function-e36c0c8c-4104-49da-ab83-82328b832349) and [here.](https://support.microsoft.com/en-us/office/time-function-9a5aff99-8f7d-4611-845e-747d0b8d5457)

**Comment by CorentinTh** [comment]
Hey @swishkin 
Thank you for the request, it's done in #704 and live : https://it-tools.tech/date-converter

![screely-1698742987525](https://github.com/CorentinTh/it-tools/assets/25065347/c865659d-985b-4291-9964-329a02b5ed0a)

**Comment by swishkin** [comment]
Thanks for the really quick turnaround on this issue, I really appreciate your work!
