### ISSUE TITLE
[BUG] Text diff tool not showing when running with the docker image

### ISSUE THREAD

**Issue by GabeDuarteM** [CorentinTh/it-tools#706]
**Which tool is impacted?**
Example: [the text diff tool](https://it-tools.tech/text-diff)

**To Reproduce**

1. Run `docker run --name it-tools --restart unless-stopped -p 8080:80 corentinth/it-tools:latest`
2. Go to localhost:8080
4. Search for `Text diff`
5. See that the tool is not found (same if you go directly to `localhost:8080/text-diff`)

**Expected behavior**
I expected all the tools present on https://it-tools.tech to also be present on the docker image version

**Screenshots**

Below you can see the url having text-diff, the 404 page, and the tool not being found when searched
![image](https://github.com/CorentinTh/it-tools/assets/7675500/bdfc034b-ec4e-481f-9b02-2c1114086705)

**Configuration (please complete the following information):**

- Device: Nobara Linux 38 (Thirty Eight)
- OS: Nobara Linux 38 (Thirty Eight)
- Browser: Brave
- Version [Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) unknown (64-bit)](https://brave.com/latest/)

**Additional context**

**Comment by CorentinTh** [comment]
Hi @GabeDuarteM 

You are currently using the `latest` tag from Docker Hub, which is linked to the most recent stable version that has been manually released. If you're looking for the absolute newest image, you should opt for the `nightly` build instead. The `nightly` build images are automatically generated each night using the latest code from the main branch.

```
docker run --name it-tools --restart unless-stopped -p 8080:80 corentinth/it-tools:nightly
```

**Comment by GabeDuarteM** [comment]
@CorentinTh Ah, makes sense, I thought https://it-tools.tech was using `latest` instead of `nightly`, thats why I was a bit confused, but thank you for clearing that out :smile:
