### ISSUE TITLE
[NEW TOOL] Word to Numeronym

### ISSUE THREAD

**Issue by lydamian** [CorentinTh/it-tools#726]
**What tool do you want?**
Example: a Word to Numeronym converter and vice versa

**Describe the solution you'd like**
text input for a word and outputs the Numeronym equivalent

e.g "Observability" => "O11y"

**Is their example of this tool in the wild?**
https://anoncom.net/tools/numeronym

**Additional context**
Add any other context about the feature request here.

**Comment by CorentinTh** [comment]
Hi @lydamian 
Thank you for the idea, it's done and live: https://it-tools.tech/numeronym-generator

![screely-1699222191905](https://github.com/CorentinTh/it-tools/assets/25065347/025371af-4a04-4dbf-8488-70aee0e9c660)

**Comment by gigamonster256** [comment]
you forgot to implement the vice-versa part 😏

**Comment by sharevb** [comment]
Héhé @gigamonster256 if it was possible ;)
