### ISSUE TITLE
[NEW TOOL] Download Time Calculator

### ISSUE THREAD

**Issue by cschaba** [CorentinTh/it-tools#734]
**What tool do you want?**
Download Time Calculator

**Describe the solution you'd like**
have a calculator to calculate the time for upload/download a file with a given size and bandwidth 

**Is their example of this tool in the wild?**
https://www.omnicalculator.com/other/download-time

**Additional context**

Thank you very much for your very nice tool!

**Comment by CorentinTh** [comment]
Hi @cschaba 
Thank you for your request 🙏🏻 

Currently, this can easily be done with the genereric [ETA calculator ](https://it-tools.tech/eta-calculator), do you see some missing features ?

**Comment by cschaba** [comment]
Hi Corentin

you are right - I have overseen this page somehow.  

Thanks for feedback :)
