### ISSUE TITLE
[NEW TOOL] Password generator

### ISSUE THREAD

**Issue by juulke100** [CorentinTh/it-tools#739]
**What tool do you want?**
A password generator

**Describe the solution you'd like**
A password generator where you can specify if uppercase characters, lowercase characters, numbers, symbols, etc are included and where you can also choose the length of the password

**Is their example of this tool in the wild?**
https://www.lastpass.com/features/password-generator#generatorTool

**Additional context**
none

**Comment by andreasseyfarth** [comment]
It might make sense to add 'password' to the keywords for token-generator.
