### ISSUE TITLE
Lack of Support for LinuxOne's S390x Architecture

### ISSUE THREAD

**Issue by WuTong2758** [CorentinTh/it-tools#767]
Description:
I've noticed that the current project does not support LinuxOne's S390x architecture. For users employing this architecture, it means the project cannot be run on their systems. S390x architecture is known for its high performance and reliability, especially in enterprise-level applications.

Why This Issue Matters:
S390x architecture is crucial in certain scenarios, particularly in enterprise environments, providing exceptional performance and reliability.
Supporting this architecture would expand the project's user base and convenience for more users.

Potential Solutions:
While I understand this may be due to specific dependencies or libraries, is there a possibility of considering support for the S390x architecture?
I'm willing to provide additional information or assist with testing to find a solution.
Thank you for addressing this issue. Looking forward to the potential support for S390x architecture, benefiting a broader range of users through this remarkable project.

**Comment by jaywehner** [comment]
This is my two cents.  I do not contribute to the development of this project. You want a open source free project to run on a enterprise class server. That in itself is a bad idea.  Maybe send the developer a bunch of money to support a enterprise software.  I know this sounds harsh.  But this is just my opnion. If security or stability is your concern then run it on red hat or a list of other secure Linux operating systems.

**Comment by WuTong2758** [comment]
Thank you for your response, and I appreciate your perspective. First and foremost, I want to express gratitude for IBM's provision of the free LinuxONE learning system and the open-source project by the it-tools team. It is through these resources that I've been able to learn and utilize these valuable tools.

I fully understand the commercial nature of the S390x architecture may raise concerns for the project manager. However, I'd like to point out that LinuxONE systems are not exclusively used in commercial settings but also find extensive use in academic and development communities, particularly as platforms for learning and practicing Linux.

I'm not insisting on immediate support for S390x in the project but rather raising the issue for discussion and exploring potential solutions. After all, this would not only benefit me personally but also contribute to the overall development of the project.

Once again, thank you for your response.
