### ISSUE TITLE
[TOOL IMPROVEMENT] docker-run-to-docker-compose-converter, supports custom indentation

### ISSUE THREAD

**Issue by northsea4** [CorentinTh/it-tools#775]
Currently, the indentation of `docker-run-to-docker-compose-converter` is 4, which is slightly less flexible.
After a brief search, I found that the tool used is `composerize.ts`, and this tool uses `yamljs` to generate yml:

https://github.com/cgoIT/composerize-ts/blob/4b2104ed539baa0b569116f6a857f8a490bf41e1/src/composerize.ts#L49
```ts
  return new ComposerizeResult(YAML.stringify(composeSpecification, 9, 4), parseResult.messages);
```
It can be seen from the source code that the indentation here is hard-coded and is fixed at 4.

It would be great if custom indentation was supported in the it-tools page.

**Comment by sharevb** [comment]
Hi @CorentinTh and @northsea4 , implemented in #845
