### ISSUE TITLE
[NEW TOOL] NS Lookup

### ISSUE THREAD

**Issue by nixe-** [CorentinTh/it-tools#776]
**What tool do you want?**
Nameserver lookup. Ie. nslookup in Linux CLI

**Describe the solution you'd like**
Simple form with domain search field, server search field and select of NS record type (A, CNAME, MX, etc...). And of course that to show records in human readable format.

**Is their example of this tool in the wild?**
There's something similar in [kloth.net](http://www.kloth.net/services/nslookup.php)

**Comment by nixe-** [comment]
Darn, my bad. My search was too narrow. This was already shot down in #412

**Comment by sharevb** [comment]
Hi @nixe-  and @CorentinTh, DNS queries over HTTPS implemented in https://github.com/CorentinTh/it-tools/pull/1371
