### ISSUE TITLE
[BUG] JSON minify output overflow screen

### ISSUE THREAD

**Issue by angelofan** [CorentinTh/it-tools#780]
**Which tool is impacted?**
JSON minify

**To Reproduce**

1. Go to [json-minify](https://it-tools.tech/json-minify)
2. Paste this JSON:
```
{
	"bot": null,
	"client": {
		"type": "browser",
		"name": "Chrome",
		"short_name": "CH",
		"version": "119.0",
		"engine": "Blink",
		"engine_version": "119.0.0.0",
		"family": "Chrome"
	},
	"os": {
		"name": "Windows",
		"short_name": "WIN",
		"version": "10",
		"platform": "x64",
		"family": "Windows"
	},
	"device": "desktop",
	"brand": "",
	"model": ""
}
```
3. See error

**Expected behavior**
The output area should all fit within the screen.

**Screenshots**
![image](https://github.com/CorentinTh/it-tools/assets/20255750/d974d193-d9fe-443b-bb7c-9afc6e381ef4)

**Configuration (please complete the following information):**

- Device: desktop
- OS: Windows 11
- Browser: Chrome
- Version: 119.0

**Additional context**
No more.

**Comment by CorentinTh** [comment]
Fixed by #787
