### ISSUE TITLE
[NEW TOOL] Base64 image encode/decode

### ISSUE THREAD

**Issue by vlasovt** [CorentinTh/it-tools#788]
I had to decode a lot of images from base64 recently and I have notice that this feature is missing from this toolset (only base64 string decoding is allowed)

Would be great to be able to decode base64 to image or encode an image to base64

Example: [Base64 Guru](https://base64.guru/converter/decode/image)

**Comment by lemon8866** [comment]
It seems you can try  "Base64 file converter"

**Comment by xiaohongred** [comment]
in current version of "Base64 file converter"
when i use "Base64 to file", it seem to must include header, just like "data:image/jpeg;base64,"
this header can in a separate input box, it would more convenience

**Comment by vlasovt** [comment]
I agree, the current feature could work but needs to be enhanced. if we could have a textfield to add a header or a dropdown for some common formats, that would help a lot.

**Comment by sharevb** [comment]
Hi @vlasovt, @xiaohongred, implemented in #905
