### ISSUE TITLE
[BUG] Using high quantity of IDs crashes site

### ISSUE THREAD

**Issue by dotvirus** [CorentinTh/it-tools#8]
**Describe the bug**
When entering more than ~10.000 into the quantity box, the UI freezes because of too many DOM updates.
Caused by https://github.com/CorentinTh/it-tools/issues/6

**To Reproduce**
1. Go to https://it-tools.tech/#/uuid-generator
2. Enter 99999
3. UI freezes

**Expected behavior**
Define an upper limit that doesn't freeze the UI

**Comment by CorentinTh** [comment]
Thank you for noticing!
I'll fix that.
