### ISSUE TITLE
[NEW TOOL] Split-Text

### ISSUE THREAD

**Issue by yqchilde** [CorentinTh/it-tools#803]
**What tool do you want?**
Example: Text Splitter

**Describe the solution you'd like**
Split into corresponding parts according to the specified delimiter, it would be even better if merging is supported.

**Is their example of this tool in the wild?**
http://www.gongjuzhu.com/gongju/g3.html

**Additional context**

**Comment by sharevb** [comment]
Hi @yqchilde, implemented in #1290

**Comment by yqchilde** [comment]
> Hi @yqchilde, implemented in #1290

good job, thanks
