### ISSUE TITLE
[NEW TOOL] PHP Array / JSON parser

### ISSUE THREAD

**Issue by Nirator78** [CorentinTh/it-tools#804]
**What tool do you want?**
Example: PHP Array to JSON parser on both side

**Describe the solution you'd like**
Add a tool to parse json to php array and the reverse side php array to json.

**Example of solution**
https://jsontophp.com/

**Comment by sharevb** [comment]
Will probably make a PR

**Comment by sharevb** [comment]
Hi @Nirator78 and @CorentinTh, implemented in #1105

**Comment by Nirator78** [comment]
Awesome, I love your tools ;)
