### ISSUE TITLE
[NEW TOOL] bar code generator

### ISSUE THREAD

**Issue by Nirator78** [CorentinTh/it-tools#805]
**What tool do you want?**
Example: a bar code generator

**Describe the solution you'd like**
Choose the barcode format then the data and after generate it.

**Is their example of this tool in the wild?**
https://barcode.tec-it.com/fr/Code128?data=1

**Comment by sharevb** [comment]
Hi @Nirator78 and @CorentinTh, implemented in #1100

**Comment by Nirator78** [comment]
Awesome, I love your tools ;)
