### ISSUE TITLE
[TOOL IMPROVEMENT] Basic auth generator: add the htpasswd output too

### ISSUE THREAD

**Issue by mikegleasonjr** [CorentinTh/it-tools#807]
**Describe the solution you'd like**
I would like to have the `htpasswd` output so I can paste it in an `.htpasswd` file with the user/pass I just entered.

**Additional context**
thanks

**Comment by sharevb** [comment]
Hi @mikegleasonjr and @CorentinTh, implemented in #902

**Comment by zmweske** [comment]
@mikegleasonjr feel free to close this issue if you are satisfied

have a great day!

**Comment by zmweske** [comment]
@mikegleasonjr sorry for the premature comment earlier- I deleted it because I realized that the code (while implemented) was not actually merged into main, so this issue is probably best left open. Sorry for the confusion- it was my fault for not looking close enough
