### ISSUE TITLE
Text ASCII Art Generator

### ISSUE THREAD

**Issue by cschwarck** [CorentinTh/it-tools#829]
**What tool do you want?**
ASCII Art text lettering. 

**Describe the solution you'd like**
Type in text that is converted into ASCII Art text lettering. This can create art you can put in your email signature, on your webpage, etc.

**Is their example of this tool in the wild?**
http://patorjk.com/software/taag/

**Additional context**
Would love to have this!

**Comment by Dlurak** [comment]
The website you mentioned seems to be powered by [this library `figlet`](https://npm.io/package/figlet), could I implement that feature using this library?

**Comment by cschwarck** [comment]
Sorry, I'm not sure of this is an option - but no issues here if that works!

**Comment by sharevb** [comment]
Hi, will be working on that soon

**Comment by sharevb** [comment]
Hi @cschwarck, @Dlurak, @CorentinTh, implemented in #886

**Comment by cschwarck** [comment]
Thank you! Much appreciated!!
