### ISSUE TITLE
[OTHER] How to enable ssl?

### ISSUE THREAD

**Issue by hcaihao** [CorentinTh/it-tools#840]
How to enable ssl?

**Comment by ag14spirit** [comment]
I believe the application runs on an  nginx web server, which would require [this configuration](https://nginx.org/en/docs/http/configuring_https_servers.html) to achieve https ssl.

**Comment by DerSilver** [comment]
Thats right, just change the config file in /etc/nginx/conf.d/default.conf

The first server is a rewrite from http to https
the second is the HTTPS server and its SSL certificates (just change ssl_certificate / ssl_certificate_key with your Paths

`server {
    listen 80;
    server_name localhost;
    
    return 301 https://$host$request_uri;
}

server {
    listen              443 ssl;
    server_name         localhost;
    ssl_certificate     conf.d/ittools-cert.pem;
    ssl_certificate_key conf.d/ittools-cert-key.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}`

**Comment by hcaihao** [comment]
> Thats right, just change the config file in /etc/nginx/conf.d/default.conf
> 
> The first server is a rewrite from http to https the second is the HTTPS server and its SSL certificates (just change ssl_certificate / ssl_certificate_key with your Paths
> 
> ```
> server {
>     listen 80;
>     server_name localhost;
>     return 301 https://$host$request_uri;
> }
> 
> server {
>     listen              443 ssl;
>     server_name         localhost;
>     ssl_certificate     conf.d/ittools-cert.pem;
>     ssl_certificate_key conf.d/ittools-cert-key.pem;
>     ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
>     ssl_ciphers         HIGH:!aNULL:!MD5;
>     root /usr/share/nginx/html;
>     index index.html;
>     location / {
>         try_files $uri $uri/ /index.html;
>     }
> }
> ```

works, tks
