### ISSUE TITLE
Unicode convert tool

### ISSUE THREAD

**Issue by nAnderYang** [CorentinTh/it-tools#850]
**What tool do you want?**
some string convert to unicode or some unicode convert to string

**Describe the solution you'd like**
any string or unicode string convert 

**Is their example of this tool in the wild?**
 iconv-lite

**Additional context**
string: `linke the string convert to unicode`
unicode string: `&#108;&#105;&#110;&#107;&#101;&#32;&#116;&#104;&#101;&#32;&#115;&#116;&#114;&#105;&#110;&#103;&#32;&#99;&#111;&#110;&#118;&#101;&#114;&#116;&#32;&#116;&#111;&#32;&#117;&#110;&#105;&#99;&#111;&#100;&#101;`

**Comment by CorentinTh** [comment]
Implemented in #858
