### ISSUE TITLE
[BUG] 127.0.0.1:5500 shows it-tools page while I didn't selfhost this  website

### ISSUE THREAD

**Issue by MMMMMoris** [CorentinTh/it-tools#884]
It is hard to reproduce this situation.
My Chrome is set to it-tools when I visit 127.0.0.1:5500 somehow.
The url does not vary but stays 127.0.0.1:5500, I didn't make any selfhost server.
Nothing changes after refreshing, relaunching browser even rebooting my PC  
There is also not programs running on port 5500

![image](https://github.com/CorentinTh/it-tools/assets/63332824/f0cc51f8-ca90-4092-a795-9df2c8f0ce17)

Command  `netstat -ano | findstr 5500` has no output.
![image](https://github.com/CorentinTh/it-tools/assets/63332824/1993b1f6-ea94-42cc-adaa-da97b00d939d)

I wonder why is this happening, it doesn't make sense.
Perhaps it is no bug, I am just curious why woud this ever happen.

**Comment by stereobooster** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API probably. Go to https://developer.chrome.com/docs/devtools/application tab and remove it there

**Comment by CorentinTh** [comment]
It may be due to the PWA, try emptying cache
