### ISSUE TITLE
[NEW TOOL] ASCII Art Generator 

### ISSUE THREAD

**Issue by Abir-Tx** [CorentinTh/it-tools#934]
**What tool do you want?**
An ASCII Art Generator tool 

**Describe the solution you'd like**
As a developer I often need ASCII arts to show them on terminal apps and in many other places too. A simple text to ASCII art generator tool will be so much helpful. An added feature can be is that it can generate with bash, python or other language support so the copy paste becomes much much easier

**Is their example of this tool in the wild?**
- [Patorjk Tool](https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20)
- [ASCII Generator]( https://ascii-generator.site/t/)

**Comment by sharevb** [comment]
Hi @Abir-Tx, already implemented.

Feel free to provide samples of bash, python...so could be implemented, thanks

**Comment by Abir-Tx** [comment]
> Hi @Abir-Tx, already implemented.
> 
> Feel free to provide samples of bash, python...so could be implemented, thanks 

I am sorry if I missed it. But I am still not finding the tool. Are you talking about the Text to ASCII binary tool? 

A simple search by ASCII keyword shows this tool only in my case. But this tool does not do ASCII arts.

**Comment by Abir-Tx** [comment]
Weird I see. I am self-hosting it using docker and the ASCII Text Drawer isn't available there idk why :(. Anyway, I see the tool exists in the official site. Thanks

Yeah that's actually right. It would be very nice if there was an option to copy the art for a specific language print statement.

**Comment by sharevb** [comment]
Hi @CorentinTh and @Abir-Tx, coding languages output added in #960

**Comment by Abir-Tx** [comment]
@sharevb loved it. Thank you so much <3

**Comment by sharevb** [comment]
Hi @Abir-Tx and for people interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

**Comment by Abir-Tx** [comment]
Hey @sharevb, great will try it out soon hopefully
