### ISSUE TITLE
If possible, add a tool for converting letters to upper and lower case

### ISSUE THREAD

**Issue by riceshowerX** [CorentinTh/it-tools#946]
For instance, one-click conversion functions include options for converting text to all uppercase, all lowercase, capitalizing the first letter of words, capitalizing the first letter of sentences, and so forth.

**Comment by CorentinTh** [comment]
Hi, thank you for taking time to make an issue :pray: 
Such tool already exists on it-tools : https://it-tools.tech/case-converter
