### ISSUE TITLE
[NEW TOOL] Days Calculator: Days Between Two Dates

### ISSUE THREAD

**Issue by riiamri23** [CorentinTh/it-tools#971]
**What tool do you want?**
Hi there, Does this web app have a calculator for calculating total days between two dates?

**Is their example of this tool in the wild?**
This is the example that i can give https://www.timeanddate.com/date/durationresult.html?d1=8&m1=9&y1=2023&d2=17&m2=11&y2=2023

**Comment by jicho** [comment]
here is another "in the wild" example: https://www.timeanddate.com/date/durationresult.html?d1=1&m1=8&y1=2024&d2=30&m2=10&y2=2024

**Comment by sharevb** [comment]
Hi @riiamri23, @jicho  and @CorentinTh, dates and duration calculators implemented in #1324

**Comment by jicho** [comment]
Thanks @sharevb!

@CorentinTh any chance that #1212 can be implemented in the new release?
