### ISSUE TITLE
[TOOL IMPROVEMENT] Bcrypt cost (rounds) limit

### ISSUE THREAD

**Issue by realgeek** [CorentinTh/it-tools#975]
**Describe the solution you'd like**
I would love it if we could set an environment variable for the Docker image to increase the maximum cost of the bcrypt tool to something greater than 10. I was working on an application recently that used a cost factor of 12 and was disappointed that I couldn't use IT-Tools to generate a new password hash for it.

**Additional context**
I used htpasswd to accomplish what I was after, and there was no noticeable wait for the output.

**Comment by sharevb** [comment]
Will make a PR soon

**Comment by sharevb** [comment]
HI @realgeek and @CorentinTh, fixed in #987
