### ISSUE TITLE
[NEW TOOL] Regex tester

### ISSUE THREAD

**Issue by agrublev** [CorentinTh/it-tools#991]
**What tool do you want?**
Regex tester

**Describe the solution you'd like**
A regex tester that allows you to enter some text and then run a regex query against it, like on https://regexr.com/. It should offer a list of predefined templates to use, such as email validation.

**Is their example of this tool in the wild?**
https://regexr.com/.

**Comment by sharevb** [comment]
Hi @agrublev  and @CorentinTh, implemented in #1030

**Comment by ouchuji** [comment]
Hi, when will the regex tester release , i readly need this tool~

**Comment by ouchuji** [comment]
@agrublev

**Comment by sharevb** [comment]
HI @CorentinTh, many people, hein dis !

**Comment by sharevb** [comment]
Hi @ouchuji , only @CorentinTh Can merge

**Comment by ouchuji** [comment]
@CorentinTh Hi~ Can you merge this pr, this pr looks stucking at open status for a long time
